### ISSUE TITLE
myVesta API not working as expected.

### ISSUE THREAD

**Issue by Tolfx** [myvesta/vesta#104]
### Describe the problem:

myVesta API doesn't work, even if I've specified which IP should be allowed to use it. I'm using Node.js which sends a POST request, with the right query.

Even tried with PHP as instructed from Vestacp owns API documents, but didn't work either.
![image](https://user-images.githubusercontent.com/57797792/107235282-d59af000-6a24-11eb-9fe8-782947c6a492.png)

### Steps to Reproduce:

* A clean installation of myVesta.
* Whitelist IP to enable API.

### Debian version:

Debian 10

### VestaCP Version:

0.9.8-26-39

### Installed Software (what you got with the installer):

ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'

**Comment by myvesta** [comment]
Did you whitelisted 127.0.0.1 as well as public ip?
Run `ifconfig` in SSH as root and see if there are other IP addresses for localhost.

**Comment by Tolfx** [comment]
> Did you whitelisted 127.0.0.1 as well as public ip?
> Run `ifconfig` in SSH as root and see if there are other IP addresses for localhost.

I have a public IP address where myVesta is using, which I included to the list as well.

**Comment by myvesta** [comment]
Well, whole whtelisting logic is here -  https://github.com/myvesta/vesta/blob/master/web/api/index.php#L4-L14

So, lets edit /usr/local/vesta/web/api/index.php
delete that block
and see if it's solved problem.

If not, then problem is not at whitelisting level.

**Comment by Tolfx** [comment]
> Well, whole whtelisting logic is here - https://github.com/myvesta/vesta/blob/master/web/api/index.php#L4-L14
> 
> So, lets edit /usr/local/vesta/web/api/index.php
> delete that block
> and see if it's solved problem.
> 
> If not, then problem is not at whitelisting level.

This didn't solve it either, but I fixed it by adding the Node.js application on the server and running it as root, then execute commands with a child process...
