### ISSUE TITLE
v-add-web-domain: line 52: if_dir_symlink: command not found

### ISSUE THREAD

**Issue by didyouexpectthat** [myvesta/vesta#105]
### Describe the problem:

/usr/local/vesta/bin/v-add-web-domain: line 52: if_dir_symlink: command not found

### Steps to Reproduce:
Fresh install of Debian 10.8. Go to install per instructions on myvesta's website. 
I used the following options
```bash vst-install-debian.sh --nginx yes --apache yes --phpfpm no --named yes --remi yes --vsftpd no --proftpd yes --iptables yes --fail2ban yes --quota yes --exim yes --dovecot yes --spamassassin yes --clamav yes --softaculous yes --mysql yes --postgresql yes --hostname HOSTNAME@FQDN.COM --email EMAIL@DDRESS.COM --password PASSWORDHERE```

Found this error in the log.
/usr/local/vesta/bin/v-add-web-domain: line 52: if_dir_symlink: command not found

### Debian version:

Debian 10.8

### VestaCP Version:

myVesta 0.9.8-26-40
Build date: 08-Feb-2021

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
DISK_QUOTA='yes'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'

###
```
=== Blocking executable files inside zip/rar/tar archives in ClamAV
2021-02-10 23:25:25 URL:http://c.myvestacp.com/tools/clamav/foxhole_all.cdb [10477/10477] -> "/var/lib/clamav/foxhole_all.cdb" [1]
Synchronizing state of spamassassin.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable spamassassin
Created symlink /etc/systemd/system/multi-user.target.wants/spamassassin.service → /lib/systemd/system/spamassassin.service.
Enabling module remoteip.
To activate the new configuration, you need to run:
  systemctl restart apache2
**/usr/local/vesta/bin/v-add-web-domain: line 52: if_dir_symlink: command not found**
/dev/vda1 [/]: group quotas turned on
/dev/vda1 [/]: user quotas turned on
dpkg-query: no packages found matching vesta-ioncube
dpkg-query: no packages found matching vesta-softaculous
```

**Comment by didyouexpectthat** [comment]
I submitted #106 for this.

**Comment by myvesta** [comment]
Fixed, thank you.
