### ISSUE TITLE
wtf does v-install-wordpress not work? I get command not found when running

### ISSUE THREAD

**Issue by Techknowledgeman** [myvesta/vesta#108]
### Describe the problem:

cannot use v-install-wordpress to install wordpress

### Steps to Reproduce:

brand new install, log into console and verify all is working, try to run v-install-wordpress domain.com

### Debian version:

Debian 10

### VestaCP Version:

0.9.8-26-42 

### Installed Software (what you got with the installer):

EB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'
UPDATE_HOSTNAME_SSL='yes'
DB_PMA_URL='
MAX_DBUSER_LEN=80
ALLOW_BACKUP_ANYTIME='yes'
NOTIFY_ADMIN_FULL_BACKUP='

**Comment by myvesta** [comment]
see https://forum.myvestacp.com/viewtopic.php?f=17&t=49

**Comment by Techknowledgeman** [comment]
> 
> 
> see https://forum.myvestacp.com/viewtopic.php?f=17&t=49

yeah thanks, I did already see that, hence my post. Setting path made zero difference and it's not that it cannot find the script, it's failing on a command inside the script from what I can see.

**Comment by myvesta** [comment]
is it working now?

**Comment by Techknowledgeman** [comment]
> 
> 
> is it working now?

no, it's not. I gave up and went to softaculous

**Comment by Techknowledgeman** [comment]
Any ideas on root cause? I'm happy to take some time to help with it.

**Comment by myvesta** [comment]
Please copy here the output from your console when you run `v-install-wordpress yourdomain.com`

**Comment by Techknowledgeman** [comment]
Sorry if I come across as a bit rough or arrogant, I don't mean to be, I just have a condition that tends to make me come across like that due to getting a bit more frustrated than most. I was just rereading and trying to imagine how it could be taken and realised it may come across that way.
The script is there and I can ls it but can't execute it. 

norgan@azure:/usr/local/vesta/bin$ ls v-install-wordpress
v-install-wordpress
norgan@azure:/usr/local/vesta/bin$ v-install-wordpress test.com
-bash: v-install-wordpress: command not found
norgan@azure:/usr/local/vesta/bin$

Just wondering if it may be permissions actually.
-rwxr-xr-x 1 root root 4455 Feb 26 11:18 v-install-wordpress

 I did also try to sudo it but same issue.

Actually, you know what it is, I'm not telling bash to execute a shell script. 
Seems, as sudo, doing sh ./v-install-wordpress is the correct command. 

If I were to share some feedback, and this goes to the entire Linux community more than you or anyone in particular; never assume anything. I've worked with Linux as a secondary os for me, being traditionally an ms engineer for decades. But syntax is a challenge for me, perhaps it is particularly for me due to my memory issues and other challenges my adhd presents me. 
I constantly find the syntax or detail missing with a lot of assumptions. It does in turn create a lot of frustration for me and adds to my replies at times as mentioned above. 

Anyway, this command, run this way, works. What is the benefit over the other one in softalicus? is it just so you don't have to subscribe, or is there some differences that may reap some benefits?

**Comment by myvesta** [comment]
The problem is simple, you must be `root` in order to execute it.
All `v-*` commands require `root` privilegis.
`sudo` maybe works, but with `sudo` you may hit another issue with undefined `$VESTA` variable.

So, solutions:
- login as root
or
- if you are logged in as user, then type: ```
su
source /etc/profile
PATH=$PATH:/usr/local/vesta/bin && export PATH
```

**Comment by myvesta** [comment]
Benefit of `v-install-wordpress`: it's free.

**Comment by Techknowledgeman** [comment]
> The problem is simple, you must be `root` in order to execute it.
> All `v-*` commands require `root` privileges.
> `sudo` maybe works, but with `sudo` you may hit another issue with undefined `$VESTA` variable.
> 
> So, solutions:
> - login as root
> or
> - if you are logged in as local user, then type:  
> ```
> su
> source /etc/profile
> PATH=$PATH:/usr/local/vesta/bin && export PATH
> v-install-wordpress test.com
> ```

Oh right, OK so root (sudo) needs the env stuff set up. Thing is though, I was running the command from it's location. Are there paths within the script that relay on this path?

**Comment by myvesta** [comment]
To be honest, not sure.
I'm always login as `root` in SSH.
I just said that **maybe** `sudo` is not passing env or PATH... but... now I remembered that whole panel is running with `sudo`....

**Comment by Techknowledgeman** [comment]
Yup, that’s it. Might want to take a look at your script to see where it’s tripping up:

root@azure:/usr/local/vesta/bin# ./v-install-wordpress frontdoor.norgan.net
Downloading WordPress 5.6.2 (en_US)...
Using cached file '/home/admin/.wp-cli/cache/core/wordpress-5.6.2-en_US.tar.gz'...
Success: WordPress downloaded.
Success: Generated 'wp-config.php' file.
Success: WordPress installed successfully.
=================================================================
Installation is complete. Your username/password is listed below.

Site: https://frontdoor.norgan.net/

Login: https://frontdoor.norgan.net/wp-admin/
Username: admin
Password: S5WmtcR2+qRQ

=================================================================
v-install-wordpress: Done.
root@azure:/usr/local/vesta/bin#

I had to actually sudo su for this.
