### ISSUE TITLE
cannot create new mariadb databases, had to rest all users just to get existing ones working. 

### ISSUE THREAD

**Issue by Techknowledgeman** [myvesta/vesta#109]
### Describe the problem:

I now have an issue where root@localhost is being denied on mariadb server. I am unsure of where this is defined to be able to update the password. 

### Steps to Reproduce:
From memory I was simply updating the admin password

### Debian version:

debian 10

### VestaCP Version:

0.9.8-26-42 

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'
UPDATE_HOSTNAME_SSL='yes'

**Comment by Techknowledgeman** [comment]
ok, the service for either mysqld or mariadb starts a separate instance to the one that myvesta starts. It was starting up before I had a chance to get in and set the root password properly.
I gave up using the systemctl services and just let vesta control mariadb. I managed to get the root user password reset in the middle of this somehow lol

Might want to either get those services disabled or make a note in docco.

**Comment by saedee** [comment]
> ### Describe the problem:
> 
> I now have an issue where root@localhost is being denied on mariadb server. I am unsure of where this is defined to be able to update the password. 
> 
> ### Steps to Reproduce:
> From memory I was simply updating the admin password
> 
> ### Debian version:
> 
> debian 10
> 
> ### VestaCP Version:
> 
> 0.9.8-26-42 
> 
> ### Installed Software (what you got with the installer):
> 
> WEB_SYSTEM='apache2'
> WEB_RGROUPS='www-data'
> WEB_PORT='8080'
> WEB_SSL_PORT='8443'
> WEB_SSL='mod_ssl'
> PROXY_SYSTEM='nginx'
> PROXY_PORT='80'
> PROXY_SSL_PORT='443'
> STATS_SYSTEM='webalizer,awstats'
> FTP_SYSTEM='proftpd'
> DNS_SYSTEM='bind9'
> MAIL_SYSTEM='exim4'
> IMAP_SYSTEM='dovecot'
> CRON_SYSTEM='cron'
> FIREWALL_SYSTEM='iptables'
> FIREWALL_EXTENSION='fail2ban'
> BACKUP_SYSTEM='local'
> LANGUAGE='en'
> VERSION='0.9.8'
> DB_SYSTEM='mysql'
> UPDATE_HOSTNAME_SSL='yes'
> 
> 

saedee_f1
