### ISSUE TITLE
vesta stopped working. Gives blank page ?

### ISSUE THREAD

**Issue by Techknowledgeman** [myvesta/vesta#111]
### Describe the problem:

Went to check my control panel today and it was just giving a blank page back

### Steps to Reproduce:

Just logging in to the panel

### Debian version:

Debian 10

### VestaCP Version:

latest

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'

**Comment by Techknowledgeman** [comment]
All other websites appear to be fine, just the control panel itself doesn't want to play with the others.

**Comment by Techknowledgeman** [comment]
[error] 805#805: *4 connect() failed (111: Connection refused) while connecting to upstream, client: xx.xx.xx.xx, server: host.host.com, request: "HEAD / HTTP/1.1", upstream: "https://x.x.x.x:8443/", host: "xx.xx.xx.xx"

**Comment by myvesta** [comment]
https://forum.myvestacp.com/viewtopic.php?f=23&t=204

**Comment by myvesta** [comment]
If port is closed, reopen the ticket.

**Comment by Techknowledgeman** [comment]
Come on man, I'm passing that secret code. This was working, exactly the same method used, but now it doesn't work.

**Comment by myvesta** [comment]
sorry.
you tried 8443 port.
8443 port is used by apache, by the way.

try to run:
`v-stop-firewall`
then check if vesta is accessible.

**Comment by Techknowledgeman** [comment]
> 
> 
> sorry.
> you tried 8443 port.
> 8443 port is used by apache, by the way.
> 
> try to run:
> `v-stop-firewall`
> then check if vesta is accessible.

That's ok, but maybe just wait or ask for more info before closing. 

I was using port 8083, but now seems to have changed for some reason? Also, it doesn't work on 8443 either. I don't know what's going on. I haven't touched the box.

**Comment by Techknowledgeman** [comment]
No difference when disabling the firewall.

**Comment by Techknowledgeman** [comment]
8443 just takes me to the default site. That works fine.

**Comment by Techknowledgeman** [comment]
From memory, I have disabled external access and only allowed the admin panel from the local backend IP. It has been working perfectly until today.

**Comment by myvesta** [comment]
Run:
`grep 'listen' $VESTA/nginx/conf/nginx.conf`
just to be sure on what port is it

**Comment by Techknowledgeman** [comment]
root@azure:/usr/local/vesta/log# grep 'listen' /usr/local/vesta/nginx/conf/nginx.conf
        listen          8083;


2021/03/09 18:43:06 [crit] 802#0: *1 connect() to unix:/var/run/vesta-php.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.100.63, server: _, request: "GET /?config HTTP/1.1", upstream: "fastcgi://unix:/var/run/vesta-php.sock:", host: "azure.syd.hosting.norgannetworks.net.au:8083"

**Comment by myvesta** [comment]
```
service vesta stop
service vesta start
```

maybe it help?

**Comment by Techknowledgeman** [comment]
also seeing this: `2021/03/02 15:19:26 [error] 851#0: *2192 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.100.63, server: _, request: "POST /softaculous/index.php?act=software&soft=26&checkhttps=frontdoor.norgan.net HTTP/1.1", upstream: "fastcgi://unix:/var/run/vesta-php.sock:", host: "hostname:8083", referrer: "https://hostname:8083/softaculous/index.php?act=software&soft=26"`

**Comment by myvesta** [comment]
maybe it's firewall on Azure virtualization level?

**Comment by Techknowledgeman** [comment]
root@azure:/usr/local/vesta/log# systemctl status vesta
● vesta.service - LSB: starts the vesta control panel
   Loaded: loaded (/etc/init.d/vesta; generated)
   Active: active (running) since Tue 2021-03-09 18:43:09 AEDT; 1h 14min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 5 (limit: 2298)
   Memory: 24.0M
   CGroup: /system.slice/vesta.service
           ├─800 nginx: master process /usr/local/vesta/nginx/sbin/vesta-nginx
           ├─802 nginx: worker process
           ├─816 php-fpm: master process (/usr/local/vesta/php/etc/php-fpm.conf)
           ├─829 php-fpm: pool www
           └─830 php-fpm: pool www

Mar 09 19:40:01 azure.syd.hosting.norgannetworks.net.au sudo[7237]: pam_unix(sudo:session): session closed for user root
Mar 09 19:45:01 azure.syd.hosting.norgannetworks.net.au sudo[7638]:     root : TTY=unknown ; PWD=/usr/local/vesta/web/softaculous ; USER
Mar 09 19:45:01 azure.syd.hosting.norgannetworks.net.au sudo[7638]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 09 19:45:01 azure.syd.hosting.norgannetworks.net.au sudo[7638]: pam_unix(sudo:session): session closed for user root
Mar 09 19:50:01 azure.syd.hosting.norgannetworks.net.au sudo[7986]:     root : TTY=unknown ; PWD=/usr/local/vesta/web/softaculous ; USER
Mar 09 19:50:01 azure.syd.hosting.norgannetworks.net.au sudo[7986]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 09 19:50:01 azure.syd.hosting.norgannetworks.net.au sudo[7986]: pam_unix(sudo:session): session closed for user root
Mar 09 19:55:01 azure.syd.hosting.norgannetworks.net.au sudo[8348]:     root : TTY=unknown ; PWD=/usr/local/vesta/web/softaculous ; USER
Mar 09 19:55:01 azure.syd.hosting.norgannetworks.net.au sudo[8348]: pam_unix(sudo:session): session opened for user root by (uid=0)
Mar 09 19:55:01 azure.syd.hosting.norgannetworks.net.au sudo[8348]: pam_unix(sudo:session): session closed for user root

**Comment by myvesta** [comment]
`curl -I "https://localhost:8083/" --insecure`
what you get here?

**Comment by Techknowledgeman** [comment]
norgan@azure:~$ curl -I "https://localhost:8083/" --insecure
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 09 Mar 2021 09:07:42 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=60

Nginx is fine, when I reboot I get bad gateway from nginx. I think something is going on with apache2 behind it.

**Comment by Techknowledgeman** [comment]
I've just noticed that pages beyond the front page are throwing a 404 error with my other sites now also.

**Comment by Techknowledgeman** [comment]
> 
> 
> Well, your myVesta is up.
> It's obviously just firewalled, probably by Azure firewall.
> 
> About other issue with sites, well, something deeply went wrong.
> I suggest clean install and migration from there - https://forum.myvestacp.com/viewtopic.php?f=14&t=50

I have no idea how you can make the statement of it being "obviously just firewalled" I am vnet local to that machine. There is no firewall in between. 
I really don't want to have to rebuild it. I'd rather understand what's wrong so I can fix it and ensure it doesn't happen again. As far as something being "deeply wrong", well yes, I agree, vesta has something deeply wrong with it. 
I'd appreciate a bit of info and guidance on what config and log files to look at.

**Comment by myvesta** [comment]
Is it possible to send me your root SSH login so I can check what's going on?
If yes, please send me private message via forum - https://forum.myvestacp.com/memberlist.php?mode=viewprofile&u=2

**Comment by Techknowledgeman** [comment]
Would a sudoer be enough? Even I don't use the root user. I'd have to get your gateway IP as well so I can allow external access.

**Comment by myvesta** [comment]
Yes, will be enough.

**Comment by myvesta** [comment]
Ping me here when you send it.

**Comment by Techknowledgeman** [comment]
Ok, it's pretty late now. I'll let you know when I'm ready.

**Comment by myvesta** [comment]
OK, just write here (on github) when you register on forum (and write your nick on forum), because first I need to approve your account on forum, then you will be able to send me private message.

**Comment by Techknowledgeman** [comment]
I have already signed up as norgan

**Comment by myvesta** [comment]
OK, 'norgan' is already approved.

**Comment by Techknowledgeman** [comment]
G'day, Seems the issue faced may have been something related to DNS propagation or some other change. I checked it this morning and it's working. Very strange. I did double-check the secret and it was correct, I also tried via the local address rather than DNS today and it worked. So root cause not known, other than maybe some kind od propagation of a setting somewhere.

**Comment by myvesta** [comment]
Can we close the ticket?
