### ISSUE TITLE
Error: Let's Encrypt validation status 400

### ISSUE THREAD

**Issue by nicokimmel** [myvesta/vesta#114]
### Describe the problem:

`Error: Let's Encrypt validation status 400` promt when enabling SSL with Let's Encrypt
`v-add-letsencrypt-domain  'admin' 'vesta.******' 'no' [Error 15]`

### Steps to Reproduce:

I dont really know. A few days ago the SSL renewing started to fail over and over again.

### Debian version:

Debian 10

### VestaCP Version:

myVesta 0.9.8-26-43

### Installed Software (what you got with the installer)

`WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'`

**Comment by Gara-SH** [comment]
if you look at the magazine, you will see this

[Thu Apr 29 13:26:14 MSK 2021] : --- Configuring challenge / STEP 4 ---
[Thu Apr 29 13:26:14 MSK 2021] : wildcard=
[Thu Apr 29 13:26:14 MSK 2021] : in /home/admin/conf/web/nginx.****.***.conf_letsencrypt we put: WRHKvlO2HIZBBu4OBQsjYmhXjZSbO1Uc8AAlFVmAb70
[Thu Apr 29 13:26:14 MSK 2021] : v-restart-proxy
[Thu Apr 29 13:26:14 MSK 2021] : --- Requesting ACME validation / STEP 5 ---
[Thu Apr 29 13:26:14 MSK 2021] : validation_check=  "status": "valid",
      "status": "valid",
[Thu Apr 29 13:26:14 MSK 2021] : for auth=https://acme-v02.api.letsencrypt.org/acme/authz-v3/12710909851
[Thu Apr 29 13:26:14 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12710909851" "" "0104GCWu4WSLbf7cmPqYMlL2lslfIS-eCfBvzZgpf3NTAa4"
[Thu Apr 29 13:26:15 MSK 2021] : answer=HTTP/2 200
server: nginx
date: Thu, 29 Apr 2021 10:26:14 GMT
content-type: application/json
content-length: 795
boulder-requester: 121628331
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 0004QyJhoJcfiSW3tSCGEd58uL6Ta31ulN7GOlGOfLKK0iw
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "www.****.***"
  },
  "status": "pending",
  "expires": "2021-05-06T10:26:13Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA",
      "token": "98ls_Jku9AxN7PnVPJFG7d6rMiN172e2YAFCnU1yTE8"
    },
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/HLp3kA",
      "token": "98ls_Jku9AxN7PnVPJFG7d6rMiN172e2YAFCnU1yTE8"
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/vefVhw",
      "token": "98ls_Jku9AxN7PnVPJFG7d6rMiN172e2YAFCnU1yTE8"
    }
  ]
}
[Thu Apr 29 13:26:15 MSK 2021] : url=https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA
[Thu Apr 29 13:26:15 MSK 2021] : token=98ls_Jku9AxN7PnVPJFG7d6rMiN172e2YAFCnU1yTE8
[Thu Apr 29 13:26:15 MSK 2021] : nonce=0004QyJhoJcfiSW3tSCGEd58uL6Ta31ulN7GOlGOfLKK0iw
[Thu Apr 29 13:26:15 MSK 2021] : status=200
[Thu Apr 29 13:26:15 MSK 2021] : --- Configuring challenge / STEP 4 ---
[Thu Apr 29 13:26:15 MSK 2021] : wildcard=
[Thu Apr 29 13:26:15 MSK 2021] : in /home/admin/conf/web/nginx.****.***.conf_letsencrypt we put: WRHKvlO2HIZBBu4OBQsjYmhXjZSbO1Uc8AAlFVmAb70
[Thu Apr 29 13:26:15 MSK 2021] : v-restart-proxy
[Thu Apr 29 13:26:15 MSK 2021] : --- Requesting ACME validation / STEP 5 ---
[Thu Apr 29 13:26:15 MSK 2021] : validation_check=
[Thu Apr 29 13:26:15 MSK 2021] : - Doing pol check on status
[Thu Apr 29 13:26:15 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA" "{}" "0004QyJhoJcfiSW3tSCGEd58uL6Ta31ulN7GOlGOfLKK0iw"
[Thu Apr 29 13:26:15 MSK 2021] : answer=HTTP/2 200
server: nginx
date: Thu, 29 Apr 2021 10:26:15 GMT
content-type: application/json
content-length: 186
boulder-requester: 121628331
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
link: <https://acme-v02.api.letsencrypt.org/acme/authz-v3/12710909851>;rel="up"
location: https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA
replay-nonce: 0004E5FhwEG2Bo_2pWQfHSlNrlSsnbhCP5kqDe_YdELfMuk
x-frame-options: DENY
strict-transport-security: max-age=604800

{
  "type": "http-01",
  "status": "pending",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA",
  "token": "98ls_Jku9AxN7PnVPJFG7d6rMiN172e2YAFCnU1yTE8"
}
[Thu Apr 29 13:26:15 MSK 2021] : validation=pending
[Thu Apr 29 13:26:15 MSK 2021] : nonce=0004E5FhwEG2Bo_2pWQfHSlNrlSsnbhCP5kqDe_YdELfMuk
[Thu Apr 29 13:26:15 MSK 2021] : status=200
[Thu Apr 29 13:26:15 MSK 2021] : sleep 4 (i=2)
[Thu Apr 29 13:26:19 MSK 2021] : - Doing pol check on status
[Thu Apr 29 13:26:19 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA" "{}" "0004E5FhwEG2Bo_2pWQfHSlNrlSsnbhCP5kqDe_YdELfMuk"
[Thu Apr 29 13:26:20 MSK 2021] : answer=HTTP/2 400
server: nginx
date: Thu, 29 Apr 2021 10:26:20 GMT
content-type: application/problem+json
content-length: 144
boulder-requester: 121628331
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: 01034tsbAZzEoqXVUpOrAEV2_sL1adcbDmFqnjOWexVESBY
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Unable to update challenge :: authorization must be pending",
  "status": 400
}
[Thu Apr 29 13:26:20 MSK 2021] : validation=
[Thu Apr 29 13:26:20 MSK 2021] : nonce=01034tsbAZzEoqXVUpOrAEV2_sL1adcbDmFqnjOWexVESBY
[Thu Apr 29 13:26:20 MSK 2021] : status=400
[Thu Apr 29 13:26:20 MSK 2021] : EXIT=Let's Encrypt validation status 400

**Comment by myvesta** [comment]
Double check if both www and non-www is pointing to your IPv4
Also, remove AAAA records in DNS.

**Comment by addictif80** [comment]
Hello,
i have a same issue, and i've checked my all of my configuration :
- My DNS records contain www.domain.tld & domain.tld pointing to the IP Server
- CloudFlare force https and SSL Crypt are desactivated
- "v-add-letsencrypt-domain" file contain "$domain" and not "$rdomain"

If you have any solution without reinstalling MyVesta, i'm will be happy because reinstallling myvesta would force me to make a full backup of all of websites and it take a very very very long time.

Best regards

**Comment by mylastore** [comment]
Same issue here both Vesta Panel SSL and any other domain on the panel.

**Comment by mylastore** [comment]
> Hello,
> i have a same issue, and i've checked my all of my configuration :
> 
>     * My DNS records contain [www.domain.tld](http://www.domain.tld) & domain.tld pointing to the IP Server
> 
>     * My DNS records don't contain any AAAA record
> 
>     * CloudFlare force https and SSL Crypt are desactivated
> 
>     * "v-add-letsencrypt-domain" file contain "$domain" and not "$rdomain"
> 
> 
> Hardware & Software config :
> 
>     * Debian 10
> 
>     * myVesta 0.9.8-26-46
> 
>     * Build date: 17-Apr-2021
> 
> 
> If you have any solution without reinstalling MyVesta, i'm will be happy because reinstallling myvesta would force me to make a full backup of all of websites and it take a very very very long time.
> 
> Best regards
> 
> EDIT
> 
> If i use the CLI command like /usr/local/vesta/bin/v-add-letsencrypt-domain USER DOMAIN ALIASES
> The Let's Encrypt certificate signin is working

Can you please tell me how you got SSL working for vestat CP ?

**Comment by myvesta** [comment]
If you have **others** NS record it means that DNS query will be forwarded to them, so, basically, you modified wrong DNS server.
And again, the only sense is that you have correctly configured DNS, which means:

- Double check if both www and non-www is pointing to your IPv4 - use https://mxtoolbox.com/DNSLookup.aspx for checking
- Remove AAAA records in DNS - use https://mxtoolbox.com/IPv6.aspx for checking (should return "**DNS Record not found**")

CloudFlare is exception, it will return it's own IPv4 and IPv6, and that's fine.

**Comment by mylastore** [comment]
> If you have **others** NS record it means that DNS query will be forwarded to them, so, basically, you modified wrong DNS server.
> And again, the only sense is that you have correctly configured DNS, which means:
> 
>     * Double check if both www and non-www is pointing to your IPv4 - use https://mxtoolbox.com/DNSLookup.aspx for checking
> 
>     * Remove AAAA records in DNS - use https://mxtoolbox.com/IPv6.aspx for checking (should return "**DNS Record not found**")
> 
> 
> CloudFlare is exception, it will return it's own IPv4 and IPv6, and that's fine.

Thanks, I resolve my issue.
