### ISSUE TITLE
Alphabetic Order is not Correct

### ISSUE THREAD

**Issue by asheroto** [myvesta/vesta#116]
### Describe the problem:

When sorting the list of users by username, it treats capital letters and lowercase letters as different characters in the sort process... Having trouble explaining this, so here's an example:

```
Bob
alice
dan
mike
```

instead of
```
alice
Bob
dan
mike
```

![image](https://user-images.githubusercontent.com/49938263/113933869-b7e6ce80-97ba-11eb-8169-1deb7246842f.png)

### Steps to Reproduce:

Create a few users starting with capital letters, and some with lowercase letters, then sort by username.

### Debian version:

Debian 10

### VestaCP Version:

0.9.8-26-43

### Installed Software (what you got with the installer):

```
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
#PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM=''
FTP_SYSTEM=''
#DNS_SYSTEM=''
MAIL_SYSTEM='exim4'
#ANTIVIRUS_SYSTEM=''
#ANTISPAM_SYSTEM=''
#IMAP_SYSTEM=''
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local,sftp'
BACKUP_GZIP='9'
LANGUAGE='en'
VERSION='0.9.8'

```

**Comment by jaapmarcus** [comment]
https://github.com/hestiacp/hestiacp/blob/d57f4def46fdcbcc6ec88f2b652b43e2bae104c5/web/templates/admin/list_user.html#L96-L97

sort-name="<?=strtolower($key)?>" Should fix the issue

**Comment by myvesta** [comment]
@jaapmarcus you mean `strtolower($key)` ?

**Comment by jaapmarcus** [comment]
Yes :)
