### ISSUE TITLE
if you look at the magazine, you will see this

### ISSUE THREAD

**Issue by Gara-SH** [myvesta/vesta#117]
if you look at the magazine, you will see this

[Thu Apr 29 13:26:14 MSK 2021] : --- Configuring challenge / STEP 4 ---
[Thu Apr 29 13:26:14 MSK 2021] : wildcard=
[Thu Apr 29 13:26:14 MSK 2021] : in /home/admin/conf/web/nginx.****.***.conf_letsencrypt we put: ******
[Thu Apr 29 13:26:14 MSK 2021] : v-restart-proxy
[Thu Apr 29 13:26:14 MSK 2021] : --- Requesting ACME validation / STEP 5 ---
[Thu Apr 29 13:26:14 MSK 2021] : validation_check=  "status": "valid",
      "status": "valid",
[Thu Apr 29 13:26:14 MSK 2021] : for auth=https://acme-v02.api.letsencrypt.org/acme/authz-v3/12710909851
[Thu Apr 29 13:26:14 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/authz-v3/12710909851" "" "****"
** ** ** **
[Thu Apr 29 13:26:15 MSK 2021] : --- Requesting ACME validation / STEP 5 ---
[Thu Apr 29 13:26:15 MSK 2021] : validation_check=
[Thu Apr 29 13:26:15 MSK 2021] : - Doing pol check on status
[Thu Apr 29 13:26:15 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA" "{}" ******
[Thu Apr 29 13:26:19 MSK 2021] : - Doing pol check on status
[Thu Apr 29 13:26:19 MSK 2021] : query_le_v2 "https://acme-v02.api.letsencrypt.org/acme/chall-v3/12710909851/W-ssLA" "{}" "****"
[Thu Apr 29 13:26:20 MSK 2021] : answer=HTTP/2 400
server: nginx
date: Thu, 29 Apr 2021 10:26:20 GMT
content-type: application/problem+json
content-length: 144
boulder-requester: 121628331
cache-control: public, max-age=0, no-cache
link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
replay-nonce: ******
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Unable to update challenge :: authorization must be pending",
  "status": 400
}
[Thu Apr 29 13:26:20 MSK 2021] : validation=
[Thu Apr 29 13:26:20 MSK 2021] : nonce=*********
[Thu Apr 29 13:26:20 MSK 2021] : status=400
[Thu Apr 29 13:26:20 MSK 2021] : EXIT=Let's Encrypt validation status 400

**Comment by myvesta** [comment]
Double check if both www and non-www is pointing to your IPv4
Also, remove AAAA records in DNS.
