### ISSUE TITLE
Rate-limit template

### ISSUE THREAD

**Issue by erikdemarco** [myvesta/vesta#118]
In rate limit template:
https://github.com/myvesta/vesta/tree/master/src/deb/for-download/tools/rate-limit-tpl

Why all try_files inside static files location block gets commented? It means it will pass the process to apache. Static files should be handled by nginx which is thier speciality because it much more faster handling static files compared to apache

**Comment by myvesta** [comment]
Commenting that line means: DON'T pass to Apache if it's not found by nginx
See last post from here https://forum.myvestacp.com/viewtopic.php?p=151#p151

**Comment by erikdemarco** [comment]
@myvesta Thnak you for the explaination. And why not write it like:
try_files      $uri  =404;

Makes it more make sense and readable.

**Comment by myvesta** [comment]
Because it's unnecessary.
Just checked, nginx returns 404 anyway...
