### ISSUE TITLE
Suggestion for utf8mb4 as default

### ISSUE THREAD

**Issue by amadexcom** [myvesta/vesta#119]
Add utfm8mb4 as default server charset, sometimes on default install the charset goes to Latin1. Who uses Latin1? No emojis.

**Describe the solution you'd like**
my.cnf

```
[client]
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4

[mysqld]
collation-server = utf8mb4_unicode_520_ci
init-connect='SET NAMES utf8mb4'
character-set-server = utf8mb4
```

**Comment by myvesta** [comment]
Done - https://github.com/myvesta/vesta/commit/d0dba33d9475966c3955114ff7dce88a1db1608a
