### ISSUE TITLE
 v-restore-user: source: not found

### ISSUE THREAD

**Issue by pantherra** [myvesta/vesta#123]
### Describe the problem:

When i trying import backup file from vestacp, im getting an error:
 v-restore-user: source: not found
 
 root@webhosting:/usr/local/vesta/bin# sh v-restore-user user user.2021-07-14_11-14-44.tar
v-restore-user: 13: v-restore-user: source: not found
v-restore-user: 32: v-restore-user: source: not found
v-restore-user: 33: v-restore-user: source: not found
v-restore-user: 34: v-restore-user: source: not found
v-restore-user: 35: v-restore-user: source: not found
v-restore-user: 36: v-restore-user: source: not found
v-restore-user: 37: v-restore-user: source: not found
v-restore-user: 168: v-restore-user: check_args: not found
v-restore-user: 169: v-restore-user: is_format_valid: not found
v-restore-user: 42: v-restore-user: [[: not found
v-restore-user: 44: v-restore-user: [[: not found
v-restore-user: 49: v-restore-user: check_result: not found
v-restore-user: 197: v-restore-user: is_object_valid: not found
v-restore-user: 199: v-restore-user: is_object_unsuspended: not found
v-restore-user: 201: v-restore-user: get_user_value: not found
v-restore-user: 210: [: Illegal number:
v-restore-user: 219: [: Illegal number:
-e
-- CRON --
-e 2021-07-14 13:30:57 1 cron job
v-restore-user: 713: v-restore-user: sync_cron_jobs: not found
v-restore-user: 716: v-restore-user: /v-restart-cron: not found
v-restore-user: 717: v-restore-user: check_result: not found
-e
**/etc/profile**
 cat /etc/profile
# /etc/profile: system-wide .profile file for the Bourne shell (sh(1))
# and Bourne compatible shells (bash(1), ksh(1), ash(1), ...).

if [ "`id -u`" -eq 0 ]; then
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
else
  PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
fi
export PATH

if [ "${PS1-}" ]; then
  if [ "${BASH-}" ] && [ "$BASH" != "/bin/sh" ]; then
    # The file bash.bashrc already sets the default PS1.
    # PS1='\h:\w\$ '
    if [ -f /etc/bash.bashrc ]; then
      . /etc/bash.bashrc
    fi
  else
    if [ "`id -u`" -eq 0 ]; then
      PS1='# '
    else
      PS1='$ '
    fi
  fi
fi

if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
LS_COLORS="$LS_COLORS:di=00;33"

### Steps to Reproduce:

Restore backup file from vesta to fresh install myvesta.

### Debian version:

Type here, example: Debian 10

### VestaCP Version:

Type here, example: 0.9.8.26-29

### Installed Software (what you got with the installer):

Copy here first 22 lines of file /usr/local/vesta/conf/vesta.conf

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'
UPDATE_HOSTNAME_SSL='yes'

**Comment by myvesta** [comment]
looks like https://forum.myvestacp.com/viewtopic.php?f=17&t=49

**Comment by myvesta** [comment]
don't use `sh`
use `bash`
