### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [myvesta/vesta#124]
@myvesta: It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by Neustradamus** [comment]
@myvesta: No lost will be here after it.

**Comment by myvesta** [comment]
What we will get if we do that?

**Comment by Neustradamus** [comment]
A better management, etc.

You can see all current organizations.

**Comment by Neustradamus** [comment]
Dear @myvesta,

Why have you closed this ticket?

It is not done!

**Comment by myvesta** [comment]
@Neustradamus 
Closed because currently I'm the only developer of myVesta, and I can't see any reason to move this repo to organization.
Maybe in the future :)

**Comment by Neustradamus** [comment]
One or more, it is better.
And to commit with a personal account too.

**Comment by Neustradamus** [comment]
Dear @myvesta team,

Can you respect the GitHub TOS?
- https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements

A human has a personal account, a project has an organization.

We can read on https://myvestacp.com/ which confirms that it is not a HUMAN:
```
myVesta is Debian fork of VestaCP that is under development by one of the VestaCP developers.
Focused on security and stability, with a lot of security improvements.
```
