### ISSUE TITLE
What are PHPmyadmin credentials?

### ISSUE THREAD

**Issue by moraisro** [myvesta/vesta#125]
What are PHPmyadmin credentials?

I cannot access phpmyadmin and it was not possible to recover mariDB root password.

**Comment by myvesta** [comment]
Credentials are username and password of database (database that you created in myVesta)

**Comment by moraisro** [comment]
Thank you!

It was easier than I thought!
It cost

**Comment by moraisro** [comment]
Hello,
I have the following situation when creating database through myVesta panel I have this error:
Error: Connection to localhost failed

The same is true when using the script: /usr/local/vesta/bin/v-install-wordpress
