### ISSUE TITLE
Connection to localhost failed

### ISSUE THREAD

**Issue by moraisro** [myvesta/vesta#126]
Hello,
I have the following situation when creating database through myVesta panel I have this error:
Error: Connection to localhost failed

The same is true when using the script: /usr/local/vesta/bin/v-install-wordpress @myvesta

**Comment by myvesta** [comment]
Did you modified `/root/.my.cnf` file or `/usr/local/vesta/conf/mysql.conf` file or `/usr/local/vesta/conf/.mysql.localhost` file ?
In all three files password should be the same.

**Comment by moraisro** [comment]
Accessing all files the passwords are the same

**Comment by myvesta** [comment]
Try to run
`sudo mysql_secure_installation`
and then set (paste) password as new password.
That should reset your mysql password.

Otherwise, I don't know, reinstall whole server.
I dont have idea how did you change mysql root password.

**Comment by myvesta** [comment]
what is happening when you run
`sudo mysql`
?

**Comment by moraisro** [comment]
I installed myvesta again. I don't know how the unforeseen happened. I'm going to run new tests on a clean install.
