### ISSUE TITLE
Código do Erro: 15  Suporte Lets Encrypt 

### ISSUE THREAD

**Issue by moraisro** [myvesta/vesta#128]
@dpeca 
@myvesta 

Error: 15 occurs when issuing Lets Encrypt on myvesta panel.

How to solve?

I have 2 website, one is normal with SSL and the other with ero 15
![erro 15](https://user-images.githubusercontent.com/87155176/129197411-1404051d-0a2a-4255-be2b-f2bc09118a9d.PNG)

**Comment by myvesta** [comment]
Get content of file **/usr/local/vesta/log/letsencrypt.log** and send me on private message on forum (user: dpeca)

**Comment by moraisro** [comment]
Solved error 15, Delete the dns from cloudflare and cleaned the dns from the server.
  I went to the vesta panel and successfully issued the Lets Encrypt SSL certificate.
