### ISSUE TITLE
404 error for dependencies

### ISSUE THREAD

**Issue by hassaan-dev** [myvesta/vesta#129]
### Describe the problem:

404 error dependencies 

### Steps to Reproduce:

I install Debian 10 on my VPS and start the installations but s

### Debian version:

Debian 10

### VestaCP Version:

Latest

### Installed Software (what you got with the installer):

E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/b/brotli/libbrotli1_1.0.7-2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/libcurl4_7.64.0-4+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/a/apache2/apache2-bin_2.4.38-3+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/a/apache2/apache2-data_2.4.38-3+deb10u3_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/a/apache2/apache2-utils_2.4.38-3+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/a/apache2/apache2_2.4.38-3+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/libj/libjpeg-turbo/libjpeg62-turbo_1.5.2-2+b1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/g/glib2.0/libglib2.0-0_2.58.3-2+deb10u2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/o/openjpeg2/libopenjp2-7_2.3.0-2+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/libw/libwebp/libwebp6_0.6.1-2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/t/tiff/libtiff5_4.1.0+git191117-2~deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/libw/libwebp/libwebpmux3_0.6.1-2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/imagemagick-6-common_6.9.10.23+dfsg-2.1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/libmagickcore-6.q16-6_6.9.10.23+dfsg-2.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/libmagickwand-6.q16-6_6.9.10.23+dfsg-2.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-common_10.3.22-0+deb10u1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/libd/libdbi-perl/libdbi-perl_1.642-1+b1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-client-core-10.3_10.3.22-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-client-10.3_10.3.22-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-server-core-10.3_10.3.22-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-server-10.3_10.3.22-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/a/avahi/libavahi-common-data_0.7-4+b1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/a/avahi/libavahi-common3_0.7-4+b1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/a/avahi/libavahi-client3_0.7-4+b1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-common_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-json_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-opcache_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-readline_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-cli_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-fpm_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-cgi_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3_7.3.14-1~deb10u1_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-xml_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/p/php-pear/php-pear_1.10.6+submodules+notgz-1.1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-intl_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-client_10.3.22-0+deb10u1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-mysql_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/roundcube/roundcube-mysql_1.3.13+dfsg.1-1~deb10u1_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-mbstring_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/roundcube/roundcube-core_1.3.13+dfsg.1-1~deb10u1_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/r/roundcube/roundcube-plugins_1.3.13+dfsg.1-1~deb10u1_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/a/awstats/awstats_7.6+dfsg-2_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/b/bind9/bind9utils_9.11.5.P4+dfsg-5.1+deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/b/bind9/bind9_9.11.5.P4+dfsg-5.1+deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/clamav-base_0.102.3+dfsg-0+deb10u1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/libclamav9_0.102.3+dfsg-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/clamav-freshclam_0.102.3+dfsg-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/clamav_0.102.3+dfsg-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/clamav-daemon_0.102.3+dfsg-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/clamav/clamdscan_0.102.3+dfsg-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/c/curl/curl_7.64.0-4+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/b/bind9/libirs161_9.11.5.P4+dfsg-5.1+deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/b/bind9/dnsutils_9.11.5.P4+dfsg-5.1+deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/d/dovecot/dovecot-core_2.3.4.1-5+deb10u2_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/d/dovecot/dovecot-imapd_2.3.4.1-5+deb10u2_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/d/dovecot/dovecot-pop3d_2.3.4.1-5+deb10u2_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/e/exim4/exim4-config_4.92-8+deb10u4_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/e/exim4/exim4-base_4.92-8+deb10u4_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/libmariadb3_10.3.22-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/postgresql-11/libpq5_11.7-0+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/e/exim4/exim4-daemon-heavy_4.92-8+deb10u4_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/e/exim4/exim4_4.92-8+deb10u4_all.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9-common_9.27~dfsg-2+deb10u3_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/cups/libcups2_2.2.10-6+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/cups/libcupsimage2_2.2.10-6+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/g/ghostscript/libgs9_9.27~dfsg-2+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/g/ghostscript/ghostscript_9.27~dfsg-2+deb10u3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/imagemagick-6.q16_6.9.10.23+dfsg-2.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/imagemagick_6.9.10.23+dfsg-2.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/l/linux/linux-libc-dev_4.19.118-2+deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/c/cairo/libcairo2_1.16.0-4_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/g/glib2.0/libglib2.0-data_2.58.3-2+deb10u2_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/libn/libntlm/libntlm0_1.5-1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/o/openexr/libopenexr23_2.2.1-4.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/i/imagemagick/libmagickcore-6.q16-6-extra_6.9.10.23+dfsg-2.1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mailutils/mailutils-common_3.5-3_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mailutils/libmailutils5_3.5-3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mailutils/mailutils_3.5-3_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/m/mariadb-10.3/mariadb-server_10.3.22-0+deb10u1_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-curl_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-gd_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/p/php7.3/php7.3-pspell_7.3.14-1~deb10u1_amd64.deb  404  Not Found [IP: 151.101.126.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/s/spamassassin/spamassassin_3.4.2-1+deb10u2_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/s/spamassassin/sa-compile_3.4.2-1+deb10u2_all.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/s/spamassassin/spamc_3.4.2-1+deb10u2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/s/sudo/sudo_1.8.27-1+deb10u2_amd64.deb  404  Not Found [IP: 128.61.240.89 80]
E: Failed to fetch http://debian.gtisc.gatech.edu/debian/pool/main/u/unzip/unzip_6.0-23+deb10u1_amd64.deb  404  Not Found [IP: 128.61.240.89 80]

**Comment by myvesta** [comment]
Obviously your Debian mirror is dead.
This is not related to mzVesta.
Install Deb10 with other apt mirror.

**Comment by hassaan-dev** [comment]
thank you for this quick response
