### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [myvesta/vesta#130]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by myvesta** [comment]
I will let you know about our email address in next 24 hours (currently we don't have it).

However, there are 5 security fixes that is reported to official VestaCP via huntr platform,, and we fixed it, but we didn't push it via update yet.
Anyway, you can get latest code by doing this:
```
rm /var/cache/apt/archives/vesta_0.9.*
apt update && apt install --reinstall vesta
```

If you want to report issues that you already report to official VestaCP, it's already fixed :)

I will make `SECURITY.md` ASAP.

**Comment by myvesta** [comment]
Here it is - https://github.com/myvesta/vesta/blob/master/SECURITY.md
Our email is info@myvestacp.com

cc @huntr-helper

**Comment by zidingz** [comment]
Thanks!

**Comment by anton-reutov** [comment]
last code from github

```
yum -y install git
cd $(mktemp -d)
git clone git://github.com/serghey-rodin/vesta.git
/bin/cp -rf vesta/* /usr/local/vesta/
```

**Comment by myvesta** [comment]
@anton-reutov 
but that's for official Vesta.
I described how to get update for this fork.
