### ISSUE TITLE
PHP Notice:  Undefined index: HTTP_ORIGIN

### ISSUE THREAD

**Issue by asheroto** [myvesta/vesta#139]
### NOTE ###
Everything works  just reporting the PHP notice in `php-fpm.log`.
### Describe the problem:

Upon browsing my server logs, `/var/log/vesta`, I noticed my `fpm-php.log` have a ton of PHP notice lines.

Functionality is 100%, no bugs, just a constant alert from Vesta CP. Same message every time.

Full path: `/usr/local/vesta/log/fpm-php.log`
Full PHP notice line:
`[26-Apr-2022 11:29:22 UTC] PHP Notice:  Undefined index: HTTP_ORIGIN in /usr/local/vesta/web/inc/secure_login.php on line 94`

It occurs at least once on each page load, sometimes more depending on the page.

I understand this is not an error, although it is ocurring because the HTTP_ORIGINAL var is not checked for existence before it is checked for logic/comparison.

### Steps to Reproduce:

SSH into Vestas CP
```
tail -f /usr/local/vesta/log/fpm-php.log
```
### Debian version:
Debian 10 (buster)
### VestaCP Version:
MyVesta 0.9.8-26-55
April 25, 2022

### Installed Software (what you got with the installer):

- maintenance scheduled enabled via cron
- Using OpenLiteSpeed (OLS)
- As mentioned, everything works fine but wanted to bring this PHP log notice to light

![image](https://user-images.githubusercontent.com/49938263/165297319-573cce14-221b-47c8-9c6f-f47ffba0d306.png)

**Comment by asheroto** [comment]
![image](https://user-images.githubusercontent.com/49938263/165298233-6bfb95ac-bc07-4b86-970e-addef0c4a117.png)

**Comment by didyouexpectthat** [comment]
Does like 94 on your secure_login.php say:
`$_SERVER['HTTP_ORIGIN'] = strtolower($_SERVER['HTTP_ORIGIN']);`

I don't have fpm-php logs at that location, but my fpm-php doesn't have this repeating line.

**Comment by asheroto** [comment]
Yes.

![image](https://user-images.githubusercontent.com/49938263/173197420-38719bf2-1c2d-4fac-915d-911f1c2d5293.png)

**Comment by myvesta** [comment]
Tnx a lot.
Fixed in latest release.
