### ISSUE TITLE
Debian 12 Support?

### ISSUE THREAD

**Issue by abdudsoul** [myvesta/vesta#160]
Support for Debian 12.

Was able to install it temporarily by forcing the codename and debian version in script to 11 and bullseye.
However i see debian 12 in /install/debian folder so when will it be officially implemented?

**Comment by myvesta** [comment]
I hope very soon, can't promise for this weekend, but I can promise this month.

**Comment by abdudsoul** [comment]
> I hope very soon, can't promise for this weekend, but I can promise this month.

Awesome! I look forward to it.

Another question, will the panel automatically upgrade the forced 11/bullseye packages i have installed to the 12/bookworm version or will I have to reinstall vesta again?

**Comment by myvesta** [comment]
I think not, because /etc/apt/sources.list.d/vesta.conf will remain untouched.
Also, spamassassin should be renamed to spamd, and few fixes more... I can't advise you to use Deb12 until we make full installation script for it 😄

**Comment by myvesta** [comment]
I think it's ready now.
Only one issue left - and it's on Debian side - it's not our bug - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038416

Of course, you have to do clean install now - it's not possible to fix all issues if you somehow installed myVesta on Deb 12 before June 19.

**Comment by abdudsoul** [comment]
> 

great! I will perform a clean install right away and get back to you with the results.

**Comment by mckaygerhard** [comment]
> I think it's ready now. Only one issue left - and it's on Debian side - it's not our bug - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038416
> 
> Of course, you have to do clean install now - it's not possible to fix all issues if you somehow installed myVesta on Deb 12 before June 19.

seems done https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038416#34

**Comment by myvesta** [comment]
https://github.com/myvesta/vesta/commit/ebd100521f3786b58540358d3cfac456fd213aef
