### ISSUE TITLE
Auto renew Lets Encrypt SSL broke custom Nginx config

### ISSUE THREAD

**Issue by theBoa** [myvesta/vesta#177]
When "Let's Encrypt SSL" is renewed, it will upload config file:
/home/USER_NAME/conf/web/DOMAIN_NAME.nginx.ssl.conf

and it destroy custom config and make it default 

myVesta 0.9.9-0-6
Build date: 22-Jan-2024
Debian 12.5

**Comment by myvesta** [comment]
First, custom configs should be implemented in templates - https://forum.myvestacp.com/viewtopic.php?f=19&t=790

Second, you can create a custom trigger script that will be executed each time LE is renewed, so you can, for example, fix certificate permissions or everything you need.
echo "UPDATE_SSL_SCRIPT='/usr/local/bin/my_custom_script.sh'" >> /usr/local/vesta/conf/vesta.conf
