### ISSUE TITLE
How do I install softaculous on myvesta?

### ISSUE THREAD

**Issue by shillshocked** [myvesta/vesta#39]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

I believe I have the latest version, but not sure if update is working correctly.

### Installed Software (what you got with the installer):

Defaults

### Steps to Reproduce:

Cannot install softaculous through GUI. Cannot install through manual procedure either, complains about ioncube missing. Cannot install ioncube. Got a friend to install softaculous manually, but he couldn't access the installed installation. It just says:

This site can’t be reached 127.0.0.1 refused to connect.

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Anything else?

**Comment by shillshocked** [comment]
Update:

Now I see there is an Apps tab in MyVesta. It links to the proper softaculous URL. But when I click on it, I get:

Page Not Found

Try start again from main page or go back to previous page

Instead of showing softaculous apps as it should. What now?

**Comment by shillshocked** [comment]
Even after resetting the MySQL password, apps tab doesn't work.

**Comment by dpeca** [comment]
I lost 3 days on this, and I'm finally on good way to solve this, but still I'm unable to make it works on deb10.
I succeeded on deb9 with official vesta-php package, but it looks like something (about mysql support) is missing on vesta-php that I compiled for deb10.
Obviously I must find a difference between official vesta-php and myVesta vesta-php, and then to recompile it.

So, temporary solution for deb9 is:

```
#!/bin/bash

if [ -f "/usr/local/vesta/web/inc/login_url.php" ]; then
    mv /usr/local/vesta/web/inc/login_url.php /usr/local/vesta/web/inc/login_url.php-bak
fi

source /etc/profile
PATH=$PATH:/usr/local/vesta/bin && export PATH

sed -i '/SOFTACULOUS/d' /usr/local/vesta/conf/vesta.conf

wget http://apt.vestacp.com/stretch/pool/vesta/v/vesta-php/vesta-php_0.9.8-26_amd64.deb -O vesta-php_0.9.8-26_amd64.deb
apt install --reinstall ./vesta-php_0.9.8-26_amd64.deb

apt-mark hold vesta-php

rm -rf /var/softaculous/
rm -rf /usr/local/vesta/softaculous/
rm -rf /usr/local/vesta/web/softaculous/

apt update
apt install --reinstall vesta-ioncube vesta-softaculous
/usr/local/vesta/bin/v-add-vesta-softaculous

if [ -f "/usr/local/vesta/web/inc/login_url.php-bak" ]; then
    mv /usr/local/vesta/web/inc/login_url.php-bak /usr/local/vesta/web/inc/login_url.php
fi
```

I will keep trying to figure out what I need to do with vesta-php on deb10.

**Comment by dpeca** [comment]
Both vesta-php are compiled with the same parameters, so issue is not there.
I'm now without ideas.

Problem we are facing is that Softaculous will throw error:
"The MySQL Connection could not be established."

If anybody have idea why Softaculous can't connect to database, I will be thankful for his help.

**Comment by dpeca** [comment]
Hmmm, just spotted that official vesta-php have:
`mysql.default_socket | /var/run/mysqld/mysqld.sock`
I will check now where it is, and is this that difference...

**Comment by dpeca** [comment]
Nothing happening even I set it in php-fpm.conf:
```
php_admin_value[mysql.default_socket] = /var/run/mysqld/mysqld.sock
php_admin_value[mysqli.default_socket] = /var/run/mysqld/mysqld.sock

```

**Comment by dpeca** [comment]
btw, PHP is able to connect to mysql using mysql_connect and mysqli->connect, just to mention it, I just tested it.

**Comment by dpeca** [comment]
btw, here is the way how to install Softaculous on Debian10:

```
#!/bin/bash

if [ -f "/usr/local/vesta/web/inc/login_url.php" ]; then
    mv /usr/local/vesta/web/inc/login_url.php /usr/local/vesta/web/inc/login_url.php-bak
fi

source /etc/profile
PATH=$PATH:/usr/local/vesta/bin && export PATH

sed -i '/SOFTACULOUS/d' /usr/local/vesta/conf/vesta.conf

rm -rf /var/softaculous/
rm -rf /usr/local/vesta/softaculous/
rm -rf /usr/local/vesta/web/softaculous/

apt update
apt install --reinstall vesta-ioncube vesta-softaculous
/usr/local/vesta/bin/v-add-vesta-softaculous

if [ -f "/usr/local/vesta/web/inc/login_url.php-bak" ]; then
    mv /usr/local/vesta/web/inc/login_url.php-bak /usr/local/vesta/web/inc/login_url.php
fi
```

... for those who want to try to solve problem with mysql...

**Comment by dpeca** [comment]
Finaly solved.
I had to recompile vesta-php with `--with-mysql-sock=/var/run/mysqld/mysqld.sock` parameter.
Looks like softaculous is doing packages installation through shell_exec with calling `/usr/local/vesta/php/bin/php`, so that's why altering php-fpm.conf was without any effect (php-cli didn't look for options in php-fpm.conf).

I will make official install-softaculous.sh script today.

**Comment by dpeca** [comment]
@shillshocked 

so, here is softaculous installer:
```
curl -O http://c.myvestacp.com/tools/install-softaculous.sh
bash install-softaculous.sh
```

**Comment by shillshocked** [comment]
Thank you, planning to give it a try.
