### ISSUE TITLE
WHMCS module not working

### ISSUE THREAD

**Issue by Vinsar** [myvesta/vesta#40]
### Operating System (OS/VERSION): 

Debian 10.2

### VestaCP Version: 

 0.9.8 (amd64)

### Installed Software (what you got with the installer):

All default optons

### Steps to Reproduce:

Try to create account from WHMCS, using Vesta module.

### Related Issues/Forum Threads:

May be because WHMCS module does not include secret URL.

### Other Notes:

WHMCS module log shows the string as "https://server.hostname.com:8083/api/user=admin&password=password&rest-of-the-string"

Solution: Either to have an option to exempt API calls from using secret URL, or option to white list WHMCS server IP, or to use a copy of Vesta/WHMCS module that is compatible with MyVesta secret URL.

**Comment by dpeca** [comment]
What is going on if secret URL is not set?

**Comment by dpeca** [comment]
... and when you delete `exit;` from first line of /web/api/index.php ?

**Comment by Vinsar** [comment]
> 
> 
> What is going on if secret URL is not set?

Not sure if that's the right method to remove secret URL validatiion, I emptied /usr/local/vesta/web/inc/login_url.php, but the result was same.

**Comment by dpeca** [comment]
No, you must completely remove `/usr/local/vesta/web/inc/login_url.php` file.

And delete `exit;` from first line of /web/api/index.php

**Comment by Vinsar** [comment]
> 
> 
> No, you must completely remove `/usr/local/vesta/web/inc/login_url.php` file.
> 
> And delete `exit;` from first line of /web/api/index.php

This worked.

But that means, no longer secret URL is in use?

**Comment by dpeca** [comment]
In next update I will make possible to whitelist some IP for API (to allow API from localhost and from some specific IP) and also whitelist for avoiding secret URL (for example to allow localhost to avoid secret URL).
I will write here when I make it.

**Comment by dpeca** [comment]
If you know PHP you can do it yourself here - https://github.com/myvesta/vesta/blob/master/web/inc/secure_login.php#L4

**Comment by dpeca** [comment]
Solved.

We now have IP whitelisting for /api/

Please run:

```
apt update
apt install vesta

mkdir -p /usr/local/vesta/conf_web
pub_ip=$(curl -s vestacp.com/what-is-my-ip/)
local_ip=$(ip addr|grep 'inet '|grep global|head -n1|awk '{print $2}'|cut -f1 -d/)

echo "$pub_ip" > /usr/local/vesta/conf_web/allow_ip_for_api.conf
if [ "$pub_ip" != "$local_ip" ]; then echo "$local_ip" >> /usr/local/vesta/conf_web/allow_ip_for_api.conf; fi
echo "127.0.0.1" >> /usr/local/vesta/conf_web/allow_ip_for_api.conf
```

and add any other IP to `/usr/local/vesta/conf_web/allow_ip_for_api.conf` that should access /api/
(each IP in new line)
