### ISSUE TITLE
Where do I find all the SSL Certificates?

### ISSUE THREAD

**Issue by shillshocked** [myvesta/vesta#46]
These are autogenerated when I add new websites. But I can only find the main one for the panel in /usr/local/vesta/ssl

Where are the other ones (as I have more than one site)?

**Comment by akz1** [comment]
my letsencrypt certs are stored at:
/home/USER/conf/web/ssl.XXX.XXXXXXXX.crt
/home/USER/conf/web/ssl.XXX.XXXXXXXX.key
