### ISSUE TITLE
Looking for help on how to manage a migration

### ISSUE THREAD

**Issue by anthonyrossbach** [myvesta/vesta#49]
I am so happy to see this project as it looks like the core VestaCP may be dead at this point, I want to be able to replace current VestaCP installs with one from a Git fork from the core project (or maybe this one) and am kinda suck on how to proceed. Is there a way you can think of to replace the ATP package on the systems so that from now on it fetches from my fork? The only downside I see to being able to switch is I currently use Ubuntu servers for everything, but will the compile also work for Ubuntu? https://github.com/myvesta/vesta/blob/master/src/deb/vesta_compile.sh

Any help with this would be amazing.

**Comment by myvesta** [comment]
myVesta supports only Debian.
Yes, you can try to compile it for Ubuntu, and bring your own apt repo...
I think I didn't use nothing specified for Debian in /bin/ scripts, buuuuut, installer has a LOT of changes, config files and templates.
So, you have to do a LOT of `diff` and to apply it in /install/ubuntu/* files.

It is very easier to backup accounts from your Ubuntu server, install Debian10, install myVesta, and then restore backuped accounts :)

**Comment by anthonyrossbach** [comment]
Ya its not really a good way as we are talking a lot of servers and accounts. Thats really why I am looking at, thats why I am thinking of using the core system as the base and using some of the changes made here. I guess I am really wondering if say moving the core from one to another can be done, really I just want to replace where it gets the updates, or maybe remove and then manually deploy the install each time to overwrite the current version (like an application)? This may be not possible but it would be the best way forward for my case I guess if it can be done. I have never had to deal with ATP or anything like this.
