### ISSUE TITLE
convert-vesta-to-myvesta.sh

### ISSUE THREAD

**Issue by arslabora** [myvesta/vesta#57]
### Operating System (OS/VERSION):

Debian9

### VestaCP Version:

Last

### Installed Software (what you got with the installer):

apache, nginx, mysql, postgresql

### Steps to Reproduce:

Run the conversion script in a freshly installed vestacp

### Related Issues/Forum Threads:

Setting up vesta-nginx (0.9.8-26-4) ...
Job for vesta.service failed because the control process exited with error code.
See "systemctl status vesta.service" and "journalctl -xe" for details.
invoke-rc.d: initscript vesta, action "start" failed.
● vesta.service - LSB: starts the vesta control panel
   Loaded: loaded (/etc/init.d/vesta; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-04-15 20:28:39 EDT; 46ms ago
     Docs: man:systemd-sysv-generator(8)
  Process: 19234 ExecStart=/etc/init.d/vesta start (code=exited, status=1/FAILURE)
    Tasks: 5 (limit: 4915)
   CGroup: /system.slice/vesta.service
           ├─331 nginx: master process /usr/local/vesta/nginx/sbin/vesta-nginx
           ├─336 nginx: worker process
           ├─369 php-fpm: master process (/usr/local/vesta/php/etc/php-fpm.conf)
           ├─371 php-fpm: pool www
           └─372 php-fpm: pool www

### Other Notes:

I would like to convert some installed servers using your script. Have you any clue why is it throwing such an error?

**Comment by myvesta** [comment]
What is the content of `/etc/apt/sources.list.d/vesta.list` file?

What do you get if you type:
```
service vesta start
journalctl -xe
```

**Comment by arslabora** [comment]
My fault! I had installed some php versions in a manner that conflicted. The script works flawlessly in a much more conventional vps. Thanks!
