### ISSUE TITLE
Wordpress Nginx + php fpm ERROR 404  permalink

### ISSUE THREAD

**Issue by vidson78** [myvesta/vesta#58]
Hello, I followed the instructions of myvesta to install everything.
bash vst-install-debian.sh
but when entering the web only the home works. index.php internal websites do not work domain.com/*
I think it is because of permalink.

use debian 10. x64
Web Template: php-fpm-73
ssl support: lets encrypt
proxy template: default

I appreciate any help you can give me the first time I use myvesta. and I really like the improvements they have.

**Comment by myvesta** [comment]
how do you installed that wordpress?
was it working and then stoped?
what do you have in error log of that domain?

**Comment by vidson78** [comment]
Thank you very much for answering.
I did the test installing wordpress from 0 and it didn't work either.
Upon further review I realized that the problem was my misconfigured cloudflare. Thank you very much myvesta for being attentive and in passing congratulate you for your great work in the community.

God bless you.

**Comment by myvesta** [comment]
Thanks :)
By the way, there are also wordpress installer script - https://github.com/myvesta/vesta/blob/master/src/deb/for-download/tools/create_wp_https

**Comment by vidson78** [comment]
Thank you.
what you recommend to use with wordpress.
since I have a lot of visits from evil bots. and ddos attacks.
Web Template:
and
proxy template:

**Comment by myvesta** [comment]
https://github.com/myvesta/vesta/blob/master/src/deb/for-download/tools/rate-limit-tpl/install_rate_limit_tpl.sh
run this installer
after that, put hosting-firewall as proxy template (or force-https-firewall)
