### ISSUE TITLE
dnc-cluster

### ISSUE THREAD

**Issue by serjiomati** [myvesta/vesta#59]
є 2 ns сервера, перший сервер знаходиться на vestacp,  другий недавно оновив до myvesta і замітив що не працює dnc-cluster. не синхронізує записи dns.

**Comment by myvesta** [comment]
try to whitelist ip of another server - https://github.com/myvesta/vesta/issues/40#issuecomment-571810051

**Comment by serjiomati** [comment]
Працює дякую

**Comment by myvesta** [comment]
Works?

**Comment by serjiomati** [comment]
yes, thx
