### ISSUE TITLE
Apache2 and Nginx not starting it boot

### ISSUE THREAD

**Issue by darkworks** [myvesta/vesta#60]
### Operating System (OS/VERSION):

Debian 10.4 

### VestaCP Version:

myVesta 0.9.8-26-20
Build date: 01-Jun-2020

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

install myveta on debian 10.4 system which have NAT IP 
and then reboot it , 
when login to vesta and go to services all services running accept apache2 and nginx there is nothing wrong with services because if you manually start them from that server services tab they will start just that it next reboot they will need manual start

### Other Notes:

Possibly something wrong with NAT IP . as when i did vesta installation it picked up router main ip like  192.168.0.20 -> xx.xx.xx.xx (public ip )   i change firewall rules on router side and also in vesta i changed public ip to different 

also i tried your script i found on vesta forum to change ip 

```
OLDIPV4='' # enter here
NEWIPV4=$(curl -s curl ipinfo.io/ip)

grep -rl "$OLDIPV4" /etc | xargs sed -i "s#$OLDIPV4#$NEWIPV4#g"
find /home/*/conf/ -type f -exec sed -i "s#$OLDIPV4#$NEWIPV4#g" {} \;
mv /usr/local/vesta/data/ips/$OLDIPV4 /usr/local/vesta/data/ips/$NEWIPV4
mv /etc/apache2/conf.d/$OLDIPV4.conf /etc/apache2/conf.d/$NEWIPV4.conf
mv /etc/nginx/conf.d/$OLDIPV4.conf /etc/nginx/conf.d/$NEWIPV4.conf
grep -rl "$OLDIPV4" /usr/local/vesta/data | xargs sed -i "s#$OLDIPV4#$NEWIPV4#g"

service bind9 restart
service apache2 restart
service nginx restart
service vesta restart
```
but looks like its only for dedicated ip address will not work in case of NAT IP 
i checked apache error log , nothing wrong with it

**Comment by myvesta** [comment]
That script will change just final IP address that nginx should bind.
You should not use it, since it probably need to bind NAT IP.

Anyway, I had that bug long long time ago, with official Vesta (and it was not Debian but CentOS).
What happened there is that system acvtivate NAT IP **after** nginx start.
So, nginx can not bind NAT IP at that moment, since NAT IP is not initialized yet :)

What I did is first to create **rc.local** script (it does not exists by default since Debian9).
```
cat <<EOF >/etc/rc.local
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

exit 0
EOF
chmod +x /etc/rc.local
systemctl daemon-reload
systemctl start rc-local
systemctl status rc-local
```

Then, in **/etc/rc.local**, before `exit 0`, I put:
```
sleep 10
service nginx restart
service apache2 restart
```

and that solved startup issue :)

**Comment by darkworks** [comment]
thanks i reinstalled it now that issue disappear for now , but during these recent multiple  tests installations i noticed that letsencrypt return 400 code everytime , however from ssh through vesta cli i was able to generate certificates but from UI always return 400 code. i did HestiaCP installation which is fork of vesta and tested letsencrypt on it , there certificates were generated , so possibly it have something to do with nat ip because on my dedicated ip vps i have not faced any  lets encrypt issue.

```
cd /usr/local/vesta/bin
v-add-letsencrypt-domain admin mydomain.com
```

one another big issue which need attention is the phpmyadmin and webmail URL if changed from settings then it return 404 not found page.

**Comment by myvesta** [comment]
admin interface actually run the same cli commands that you run manually...
you can check /usr/local/vesta/log/error.log to see it...
or maybe it uses additional parameters for NAT... please check error.log to see what is exxecuted.

currently we don't have command for changing phpmyadmin url, i'm sorry.
i will make it in futured releases.

**Comment by darkworks** [comment]
i deleted and re added domain and try to generate certificate but same error

![image](https://user-images.githubusercontent.com/12841788/84345453-db56e200-abc6-11ea-8ab9-546ee427fe97.png)

now i checked error log again 

2020-06-10 18:32:33 v-add-letsencrypt-domain  'admin' 'mysite.com' 'www.mysite.com' 'no' [Error 15]

so the problem seems to be as when UI try to generate certificates from UI it can call CLI like that
`v-add-letsencrypt-domain  'user' domain.com www.domain.com  `
mean problem is with Alias it call for both

**Comment by myvesta** [comment]
but now you don't have twice test.mysite.com like in first example.

first time when you tried, did you created domain as **somethig.com** or **www.somethig.com** ?

**Comment by darkworks** [comment]
> but now you don't have twice **test.mysite.com** like in first example.
> 
> first time when you tried, did you created domain as **somethig.com** or **[www.somethig.com](http://www.somethig.com)** ?

ya because earlier Alieases was like this

```
www.something.com       # default
something.com               # i had added
```
so i thought it maybe due to 2nd alias which i added so i deleted that web domain and re added so by default vesta  use  www.something.com  alias

**Comment by myvesta** [comment]
well, probably that caused a bug.
you should never type **www.** while creating domain in Vesta.
just add naked domain.com, without www.

in that case letsencrypt will be called properly from frontend:
`v-add-letsencrypt-domain 'admin' 'mysite.com' 'www.mysite.com' 'no'`

in such way i never experienced a bug.

**Comment by darkworks** [comment]
well  i have not used any www with domain entry when adding domain its just vesta by default add www. with alias when it fill the form auto

![image](https://user-images.githubusercontent.com/12841788/84375115-7fa54c80-abf8-11ea-896c-f6a71cb48abb.png)

like this 
![image](https://user-images.githubusercontent.com/12841788/84375219-acf1fa80-abf8-11ea-987f-12bc6a1e8725.png)

**Comment by myvesta** [comment]
www. in alias is just fine (it's auto-generated)

so, try to generate letsencrypt now...
just do it from another server because from current you reached maximum numbers of try.
make sure both domain.com and www.domain.com is pointing to server ip.

**Comment by darkworks** [comment]
i tried again but same 400 error code

`2020-06-11 02:41:38 v-add-letsencrypt-domain  'admin' 'erp.surfaceart.com' 'www.erp.surfaceart.com' 'no' [Error 15]
`
this could be  because i can visit my site without www but cant visit  with www

so i did another try during adding domain i removed www  from alias  as vesta add www by default

after that i start getting  `Error: Let's Encrypt new auth status 429`

```
2020-06-11 02:43:32 v-add-letsencrypt-domain  'admin' 'erp.surfaceart.com' 'erp.surfaceart.com' 'no' [Error 15]
2020-06-11 02:45:02 v-add-letsencrypt-domain  'admin' 'erp.surfaceart.com' 'erp.surfaceart.com' 'yes' 'yes' [Error 15]
```

**Comment by myvesta** [comment]
First, there is no need to repeat the same host.
So, instead:
`v-add-letsencrypt-domain 'admin' 'sub.domain.com' 'sub.domain.com' 'no'`
you should call:
`v-add-letsencrypt-domain 'admin' 'sub.domain.com' '' 'no'`
also, make sure Alias field is empty, since you can't access www.sub.domain.com

Second, LetsEncrypt is failing because you don't have A record for www.
That's a root of your prroblem.

So, either create A record for www.sub.domain.com or just remove www alias.
In command line it will be:
`v-add-letsencrypt-domain 'admin' 'sub.domain.com' '' 'no'`

Third, you probably hit max count of LetsEncrypt tries.

**Comment by darkworks** [comment]
well i have A record for sub domain is its auto generated by vesta but not sure why cant access with www.

anyway i deleted and added domain again by leaving alias section blank as you suggested , it returned 429 error

`2020-06-11 04:20:04 v-add-letsencrypt-domain  'admin' 'sub.domain.com' '' 'no' [Error 15]`

**Comment by myvesta** [comment]
letsencrypt 429 error means you reached limit of max tries.
try again after a few hours.
https://community.letsencrypt.org/t/error-429-too-many-requests/98580/2

**Comment by darkworks** [comment]
ever after 10 hours am still getting 429 not sure after how much time they allow domain again for retry .

**Comment by myvesta** [comment]
make sure
**/usr/local/vesta/data/queue/letsencrypt.pipe**
is empty

**Comment by darkworks** [comment]
ya i checked it was not empty , i made it empty and then retry and got same 429 error :(

**Comment by myvesta** [comment]
sorry, can't help you about it :(

**Comment by darkworks** [comment]
no do not say like that , you helped a lot :) am thankful to you .

**Comment by myvesta** [comment]
if it's cloud, make snapshot and bring it on new IP.

It's easy to replace IP on whole system:
```
OLDIPV4=''
NEWIPV4=''

grep -rl "$OLDIPV4" /etc | xargs sed -i "s#$OLDIPV4#$NEWIPV4#g"
find /home/*/conf/ -type f -exec sed -i "s#$OLDIPV4#$NEWIPV4#g" {} \;
mv /usr/local/vesta/data/ips/$OLDIPV4 /usr/local/vesta/data/ips/$NEWIPV4
mv /etc/apache2/conf.d/$OLDIPV4.conf /etc/apache2/conf.d/$NEWIPV4.conf
mv /etc/nginx/conf.d/$OLDIPV4.conf /etc/nginx/conf.d/$NEWIPV4.conf
grep -rl "$OLDIPV4" /usr/local/vesta/data | xargs sed -i "s#$OLDIPV4#$NEWIPV4#g"

service bind9 restart
service apache2 restart
service nginx restart
service vesta restart
```

**Comment by darkworks** [comment]
i think this will not work on NAT or on nat i just need to change ip it
router level for this vm local ip. i will try on that.

**Comment by myvesta** [comment]
NAT IP will stay unchanged, just replace public IP.

**Comment by darkworks** [comment]
ya right i will change it just that it will need some time to propagate.

**Comment by darkworks** [comment]
thanks finally problem solved :)
