### ISSUE TITLE
locked out of vestacp after secret url

### ISSUE THREAD

**Issue by sennevb** [myvesta/vesta#61]
Hello,

I moved from vestacp to myvestacp with your script.
So far so good!
after that i set the secret url using:
echo "<?php \$login_url='MY-SECRET-URL';" > /usr/local/vesta/web/inc/login_url.php
Now i get blank page when i want to go to the normal controlpanel, wich is good, but when i use the url i just set, i get a page not found error.

the php is there, i check using nano, i also tried putting a ?> closing tag after it, but still same problem

removed the php file for now so i can enter the CP again

Help appreciated

**Comment by sennevb** [comment]
Maybe i has to do with a bad upgrade? i got a few errors in console when upgrading:
Setting up vesta (0.9.8-26-20) ...
find: ‘/etc/php/*/fpm/pool.d/’: No such file or directory
sed: no input files
sed: no input files
find: ‘/etc/php/*/fpm/pool.d/’: No such file or directory
sed: no input files
sed: no input files
find: ‘/etc/php/*/fpm/pool.d/’: No such file or directory
sed: no input files
sed: no input files
Too few arguments.
=== patching clamav-daemon.service
=== scheduling keeping-mpm-event check script
=== myVesta 0.9.8-26-20 updated ===
=== myVesta build date: 01-Jun-2020
Setting up vesta-nginx (0.9.8-26-4) ...
Installing new version of config file /usr/local/vesta/nginx/conf/nginx.conf ...
=== Restarting vesta ===
Setting up vesta-php (0.9.8-26-4) ...
Processing triggers for systemd (232-25+deb9u12) ...

I see that i am still on debian 9, maybe that is the issue, can i upgrade to 10 without issues or should  i keep it like it is at the moment, i dont want to break things?

**Comment by myvesta** [comment]
You tried to access hosting panel with this URL format:
https://hostname:8083/?secreturl
?

btw, just simply remove **/usr/local/vesta/web/inc/login_url.php** and everything will went to normal.

also check that file, maybe there is some syntax error.

**Comment by sennevb** [comment]
The questionmark did the trick!! Thanks! And as stated above i figured removing the file would fix it for now
