### ISSUE TITLE
php-fpm

### ISSUE THREAD

**Issue by 1webdomain** [myvesta/vesta#64]
Operating System (OS/VERSION):
Debian 10.4
VestaCP Version:
myVesta 0.9.8-26-23 Build date: 14-Jun-2020

Installed Software (what you got with the installer):
apache, nginx, mysql + multi-php-install.sh

Steps to Reproduce:

in web template apache2 i see
PHP-FPM-56
PHP-FPM-70
PHP-FPM-71
PHP-FPM-72
PHP-FPM-73
PHP-FPM-74
PHP-FPM-73-public
PHP-FPM-74-public
default
hosting

but into file vst-install-debian.sh i see phpfpm setting = no !!!!
# Defining default software stack
set_default_value 'nginx' 'yes'
set_default_value 'apache' 'yes'
set_default_value 'phpfpm' 'no'

1) php-fpm can you clarify if it is correct?

2) difference between PHP-FPM-73 and PHP-FPM-73-public ?

**Comment by myvesta** [comment]
`set_default_value 'phpfpm' 'no'`

official vesta knows only two types of installation:
- nginx + apache (php inside apache) = default
- nginx + php-fpm = second option

Stuff is little different on myVesta.
Default stack is:
- nginx + apache + php-fpm
(by the way, apache is installed in mpm_event mode, so it's fast as nginx)

If you choose php-fpm installation (equal to second option in official vesta) - you will probably get **nginx + php-fpm** (without apache), except that i never tried that option, and i'm not sure if it works good.

Anyway, either you installed system with Apache - you can easily skip Apache and connect directly nginx and php-fpm - here is how - https://forum.vestacp.com/viewtopic.php?p=71226#p71226

PHP-FPM-73-public is for Laravel, and only difference is that webroot is **public_html/public/** insted of **public_html/**

**Comment by 1webdomain** [comment]
THX very very good and very comprehensive answer. 
i tested this iotheme theme on myvestacp debian 10 and it works great. very attractive look!
[vesta_iotheme.tar.gz](https://github.com/myvesta/vesta/files/4783088/vesta_iotheme.tar.gz)

**Comment by myvesta** [comment]
Yes, I tested it too... very nice look... I will consider implementing.

**Comment by 1webdomain** [comment]
Also this plg run fine >>>> https://github.com/SS88UK/VestaCP-Tools-Plugin/blob/master/index.php

**Comment by 1webdomain** [comment]
this is screenshot https://blog.ss88.us/vestacp-tools-plugin

**Comment by myvesta** [comment]
nginx + php-fpm variant (without apache) now works.
i just fixed installer issues.

**Comment by 1webdomain** [comment]
ok very good, i have make a free filemanager for myvestacp elfinder 2.1.57 based, it is ok for admin, but i do not know how to setup it for only users, in connector.minimal.php for admin it is this code:
$user 	  	= $_SESSION['user'];
$url 	  	= dirname($_SERVER['PHP_SELF']) . '/list/elfinder';
$path 	  	= '/home/' . $user . '/web';
$alias 	  	= '/home/' . $user;
can you tell me how to setup code for users only, so any users can see only own domains and not all server domains?

**Comment by myvesta** [comment]
Sorry, I don't have free time for help with 3rd party software :(

**Comment by 1webdomain** [comment]
sorry too it will be a good plus also for you. i will not disturb anymore.have a good day

**Comment by myvesta** [comment]
No worry, you are not disturbing me brother, i'm just saying that I really can't handle it now :)
Please keep posting sugestions, we have forum now - http://forum.myvestacp.com/
