### ISSUE TITLE
apache 2 new version ?

### ISSUE THREAD

**Issue by 1webdomain** [myvesta/vesta#65]
### Operating System (OS/VERSION):

Debian 10.4

### VestaCP Version:

myVesta 0.9.8-26-20
Build date: 014-Jun-2020

### Installed Software (what you got with the installer):
 php-fpm, apache, nginx, mysql

### Steps to Reproduce:

Apache/2.4.38 (Debian)
Server built:   2019-10-15T19:53:42

### Related Issues/Forum Threads:

is it possible latest version of Apache 2.4.43 ?

### Other Notes:

THX

**Comment by myvesta** [comment]
Apache version is directly conducted by Debian apt repo, so can't change that...
You can only try to find Apache apt repo and install latest Apache, or to compile it yourself.
