### ISSUE TITLE
v-add-remote-dns-host

### ISSUE THREAD

**Issue by sandsjh** [myvesta/vesta#66]
Does 

v-add-remote-dns-host slave.yourhost.com 8083 admin p4sw0rd

work with the special URL?

Is there a forum for myvesta? Can't find one and vestacp forum is DEAD.

**Comment by myvesta** [comment]
Check this - https://wiki.myvestacp.com/index.php?title=DNS_cluster_is_not_working

I'm working to setup forum.

**Comment by sandsjh** [comment]
https://forum.myvestacp.com/viewtopic.php?f=10&t=585
