### ISSUE TITLE
iotheme template with myTooLs and elfinder OK

### ISSUE THREAD

**Issue by 1webdomain** [myvesta/vesta#72]
[myvesta.zip](https://github.com/myvesta/vesta/files/4855839/myvesta.zip)
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

myVesta 0.9.8-26-26 Build date: 27-Jun-2020

### Installed Software (what you got with the installer):

php-fpm, apache, nginx, mysql

### Steps to Reproduce:

iotheme template with myTooLs and elfinder 
>>>> scp /home/accountName/myvesta_iotheme.tar.gz root@xxx.yyy.zzz.kkk:/usr/local/vesta/
>>>> ssh root@xxx.yyy.zzz.kkk
>>>> cd /usr/local/vesta && sudo tar -xvf /usr/local/vesta/myvesta_iotheme.tar.gz -C /usr/local/vesta/web

### Related Issues/Forum Threads:

it is ok with more then 3 vps

### Other Notes:

Anything else?
[myvesta_iotheme.tar.gz](https://github.com/myvesta/vesta/files/4855842/myvesta_iotheme.tar.gz)

**Comment by myvesta** [comment]
Will check <3

**Comment by 1webdomain** [comment]
do you check it ?

Il giorno mer 1 lug 2020 alle ore 09:31 myvesta <notifications@github.com>
ha scritto:

**Comment by 1webdomain** [comment]
no answer

**Comment by 1webdomain** [comment]
switch to another panel, no anwers

**Comment by myvesta** [comment]
Looking good, as I already said on forum.
But for now we will stay with default theme, sorry :/
