### ISSUE TITLE
vestacp does have postfix with dovecot ?

### ISSUE THREAD

**Issue by darkworks** [myvesta/vesta#73]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

0.9.8-26

### Installed Software (what you got with the installer):

 php-fpm, apache, nginx, mysql

### Steps to Reproduce:

am trying to switch dovecot to mysql authentication so that i can add mail user directly just by modifying db from my php application , currently vestacp is saving passwords on disk , so i searched on mysql authentication and all most all guides are based on postfix + dovecot , so is it safe to install postfix along vestacp.
also anyway to switch existing dovecot to mysql auth directly without postfix. so that vestacp not break due to it.

### Related Issues/Forum Threads:
https://workaround.org/ispmail/wheezy/setting-up-dovecot

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Anything else?

**Comment by myvesta** [comment]
Postfix is not supported in Vesta.
Yes, everything is possible if you modify vesta scripts... but on next myVesta update your modified scripts will be overwitten... so... not good idea... except if you make your own fork.
Why not call `sudo /usr/local/vesta/bin/v-add-mail-account` from your PHP code instead to add mysql row?
Yes, in that case you need to remove `shell_exec` from disabled_functions in php.ini

**Comment by darkworks** [comment]
ya you right , i was also thinking of enabling `shell_exec` and calling vesta cli

**Comment by myvesta** [comment]
Fun fuct:
- you can remove `disable_functions` from in **php.ini**
- and move `disable_functions` one level down, in **pool.d** config files
- in domain that you need `shell_exec` just remove `shell_exec` (it can be some subdomain dedicated only for work with Vesta command)

Bonus pack:
- php scripts in **/usr/local/vesta/custom/** folder WILL NOT be overrided nor removed.
So you can also put script under the myVesta, just you will have php 5.6 :)

**Comment by darkworks** [comment]
thanks for amazing tips :) vesta is big world we need to keep it exploring and building it .

**Comment by myvesta** [comment]
Third solution - you can send POST request (from your PHP) to https://yourhost:8083/api/index.php 😄 
Just first enable it - https://wiki.myvestacp.com/index.php?title=Why_API_is_not_working%3F

**Comment by darkworks** [comment]
great :)

**Comment by darkworks** [comment]
i tried to call vesta command from web root like

`exec ("sudo /usr/local/vesta/bin/v-list-mail-accounts "admin domain.com, $output, $return_var);`

and getting blank response
`Array ( [0] => ACCOUNT ALIAS FWD DISK DATE [1] => ------- ----- --- ---- ---- )`

however the same script when i run from ssh bash shell as root like `php myscript.php`  i get correct output of all mail accounts on terminal , 

so looks like when executed under apache php-fpm there is permission issue.  

i have chroot enabled so do u think its issue ? i had created link of that vesta command to web root so that can be execute in webroot but no success same blank response.

**Comment by myvesta** [comment]
maybe issue with $VESTA env variablle.

try:
`exec ("source /etc/profile && PATH=$PATH:/usr/local/vesta/bin && export PATH && sudo /usr/local/vesta/bin/v-list-mail-accounts admin domain.com", $output, $return_var);`

**Comment by darkworks** [comment]
> maybe issue with $VESTA env variablle.
> 
> try:
> `exec ("source /etc/profile && PATH=$PATH:/usr/local/vesta/bin && export PATH && sudo /usr/local/vesta/bin/v-list-mail-accounts admin domain.com", $output, $return_var);`

its returning blank array and  127 code in `$output, $return_var`

`Array ( ) 127`

**Comment by myvesta** [comment]
is that domain/subdomain under admin account?

**Comment by darkworks** [comment]
ya its under admin.

**Comment by myvesta** [comment]
`exec ("VESTA=/usr/local/vesta && export VESTA && sudo /usr/local/vesta/bin/v-list-mail-accounts admin domain.com", $output, $return_var);`

tested, works 😉
