### ISSUE TITLE
phpmyadmin error

### ISSUE THREAD

**Issue by dzagu** [myvesta/vesta#74]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

Newest

### Installed Software (what you got with the installer):

All default

### Steps to Reproduce:

When i login to db in phpmyadmin i get those errors
Zapytanie SQL: DokumentacjaEdytuj Edytuj

SELECT `comment`
                FROM `phpmyadmin`.`pma__column_info`
                WHERE db_name     = 'admin_1test'
                    AND table_name  = ''
                    AND column_name = '(db_comment)'
MySQL zwrócił komunikat: Dokumentacja

#1932 - Table 'phpmyadmin.pma__column_info' doesn't exist in engine

### Related Issues/Forum Threads:

Found anything that might be related to this? It might help us find the cause.

### Other Notes:

Anything else?

**Comment by myvesta** [comment]
is it nginx-php-fpm variant?

**Comment by dzagu** [comment]
I dont know, its fresh setup, all default settings. I messed up something in database.

**Comment by myvesta** [comment]
can you copy here first 5 lines of `/usr/local/vesta/conf/vesta.conf`

**Comment by dzagu** [comment]
Nevermind, fixed with this https://github.com/skurudo/phpmyadmin-fixer

**Comment by myvesta** [comment]
Bug found, fixed for new installations - https://github.com/myvesta/vesta/commit/a3dba232b7e0b93e967203d761fb7451e0286b40
Thank you.
