### ISSUE TITLE
unable to set php.ini value 

### ISSUE THREAD

**Issue by darkworks** [myvesta/vesta#75]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

latest build 26.

### Installed Software (what you got with the installer):

 php-fpm, apache, nginx, mysql

### Steps to Reproduce:

- click on server menu 
- click on apache configure button
- click on configure php.ini
- enter max execution time 300
- save it
- reload you will see that these fields are blank 

on top of that php.ini files it ` /etc/php/7.x/fpm/php.ini` are overwritten and backuped there and php.init just contain 
`Usage: CONFIG`

i set execution time in `/etc/php/7.x/fpm/pool.d\mydomain.com`

but its not effecting , still have difficult 30 sec 

so wondering how can we over write php execution time

**Comment by myvesta** [comment]
first, don't change php.ini via frontend interface.
secondly, edit `/etc/php/7.x/fpm/pool.d/mydomain.com.conf`
if you change execution time then also alter `request_terminate_timeout` in the same conf file.
and thirdly, restart php-fpm after that: `service php7.x-fpm restart`

**Comment by darkworks** [comment]
oh i see i had not changed `request_terminate_timeout`

thanks
