### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jstacklin** [myvesta/vesta#77]
Hello, I am trying on a clean install but get the following:

`vst-install-debian.sh: line 528: [: buster/sid: integer expression expected
E: Malformed entry 1 in list file /etc/apt/sources.list.d/vesta.list (absolute Suite Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/vesta.list (absolute Suite Component)
E: The list of sources could not be read.
E: Malformed entry 1 in list file /etc/apt/sources.list.d/vesta.list (absolute Suite Component)
E: The list of sources could not be read.
Error: apt-get install failed`

Running on Ubuntu 18.04.1 since Debian 10 doesn't work on my install of Hyper-V and I can't figure out how to use the Debian site to get an older version. 18.04.1 is based on Deb10 so shouldn't have any issues tho, correct?

**Comment by myvesta** [comment]
I think there is no way to run myVesta on Ubuntu.
Better try www.hestiacp.com fork for Ubuntu.
