### ISSUE TITLE
Error: Let's Encrypt validation status 400 when checking Let's Encrypt support checkbox

### ISSUE THREAD

**Issue by asheroto** [myvesta/vesta#79]
### Operating System (OS/VERSION):

Debian 10

### VestaCP Version:

myVesta 0.9.8-26-28
Build date: 15-Jul-2020

### Installed Software (what you got with the installer):

defaults

### Steps to Reproduce:

Add Let's Encrypt support to any domain (via checkbox)

### Related Issues/Forum Threads:

https://forum.vestacp.com/viewtopic.php?t=18597
https://community.letsencrypt.org/t/error-lets-encrypt-validation-status-400/99289/2

### Other Notes:

I get this on all of my domains.

![image](https://user-images.githubusercontent.com/49938263/87793753-49687780-c80b-11ea-8b24-44856a88bcd9.png)

**Comment by icodeerror** [comment]
I'm also facing `Let's Encrypt validation status 400` after updating to **myVesta 0.9.8-26-28**

**Comment by myvesta** [comment]
Can you confirm that both **domain.com** and **www.domain.com** is pointing to IP of your server?
Check it here - https://mxtoolbox.com/DNSLookup.aspx

I'm sure there is no bug, I have 100 servers, and myVesta is installed on  (at least) 360 servers, so probably you are doing something wrong.

**Comment by myvesta** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/38690722/87806909-e05b2100-c857-11ea-8dcf-d3fbe0e01a8f.png)
Just tested.

**Comment by asheroto** [comment]
Yeah I think it was because I use Cloudflare.  If it's proxied on the DNS settings then of course the destination domain's IP will be theirs.  Sorry!

**Comment by myvesta** [comment]
I'm pretty sure it works even if domain is behind CF proxy.

BTW, you don't need LetsEncrypt in that case.
See changelog for Version 0.9.8-26-26 [27-Jun-2020] - https://forum.myvestacp.com/viewtopic.php?p=115#p115
`* [Feature] Self-signed SSL will be automaticaly added when you add new domain (CloudFlare is fine with that, you don't need LetsEncrypt anymore if you use CloudFlare as reverse-proxy(CDN+Firewall), just set "Full" in SSL section on CloudFlare)`
