### ISSUE TITLE
Method for importing vestacp backup

### ISSUE THREAD

**Issue by wjstone** [myvesta/vesta#80]
### Describe the problem:

I've tried manually copying a backup to the server but i cannot restore it.
### Steps to Reproduce:

Type here what we should do in order to see the bug on our test server

### Debian version:

Debian 10
### VestaCP Version:

myVesta 0.9.8-26-28

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'

**Comment by myvesta** [comment]
How did you tried to restore it?
What error you got?

**Comment by wjstone** [comment]
I copied to backup to /backup and tried using v-restore-user like i would on vesta

**Comment by myvesta** [comment]
Copy here command line you executed, and output.

**Comment by wjstone** [comment]
root@localhost:/home/backup# v-restore-user admin admin.2020-07-20_17-43-13.tar
-bash: v-restore-user: command not found

**Comment by myvesta** [comment]
Looks like you just installed myVesta, and you are still in that SSH connection.
In that case (and only in that case) first you must run:
```
source /etc/profile
PATH=$PATH:/usr/local/vesta/bin && export PATH
```

Then you can call v- commands.

**Comment by wjstone** [comment]
That did it,  I can't believe I missed it.  Thanks!

**Comment by myvesta** [comment]
Yes, installer (as child process) really does not have a way to alter ENV variables in parrent bash... so only way is to start again new SSH connection (that will load new ENV paths and variables), or to execute manually those two commands :)
