### ISSUE TITLE
[Feature Request] tool to convert myvesta to vesta

### ISSUE THREAD

**Issue by ipkpjersi** [myvesta/vesta#82]
Hello,

I am requesting a feature for a tool to convert myvesta to vesta. It is awesome that vesta can be converted to myvesta - but of course, it is a bit daunting that it is a one-way conversion.

Thanks.

**Comment by myvesta** [comment]
https://forum.myvestacp.com/viewtopic.php?f=14&t=50
the same way is for myvesta to vesta

**Comment by ipkpjersi** [comment]
I must admit - I'm confused. 

There is a script (tool) for converting vesta to myvesta: https://github.com/myvesta/vesta/blob/master/src/deb/for-download/tools/convert-vesta-to-myvesta.sh

I am wondering if there could be one to do the reverse, going from myvesta to vesta?

**Comment by myvesta** [comment]
You are right.
But, in fact, i'm not recommending that convert script because A LOT of myVesta features will not be 'added' that way.
I will add now note to that script that script is not recommnended way to do migration.
Much better way is clean install and importing backup, as described, and can be done in both ways.

**Comment by myvesta** [comment]
Added - https://github.com/myvesta/vesta/commit/348cecb0e98e34307877aa508071ba7ae5b7531b

BTW, what Debian version you have on that server that you want to convert to Vesta?

**Comment by ipkpjersi** [comment]
Hi,

I think it was 9. It's not necessarily that I need to convert it or anything, I just think it would be nice to have the option to switch between the two. 

It's good to know that it's not recommended to migrate using that script.

Thanks.

**Comment by myvesta** [comment]
Well, let's try:
```
wget -O - http://c.vestacp.com/deb_signing.key | sudo apt-key add -
codename="$(cat /etc/os-release |grep VERSION= |cut -f 2 -d \(|cut -f 1 -d \))"
echo "deb http://apt.vestacp.com/$codename/ $codename vesta" > /etc/apt/sources.list.d/vesta.list
apt update
apt install -y vesta vesta-php vesta-nginx

service vesta stop
service vesta start
```

**Comment by ipkpjersi** [comment]
Yep, that looks good to me, that was what I was looking for. I'd say that's probably worth committing to the repo alongside the script that does it in the other direction along with the warning that it's not recommended.

**Comment by myvesta** [comment]
From https://github.com/serghey-rodin/vesta/blob/master/install/vst-install-debian.sh

```

RHOST='apt.vestacp.com'
CHOST='c.vestacp.com'
echo "deb http://$RHOST/$codename/ $codename vesta" > $apt/vesta.list
wget $CHOST/deb_signing.key -O deb_signing.key
```
so I think that's it :)

I know that apt repo has the same folder structure, I made so because easy replace to myvesta url.
