### ISSUE TITLE
How to Allow SFTP user to ssh

### ISSUE THREAD

**Issue by darkworks** [myvesta/vesta#83]
### Describe the problem:

i wonder how can we allow sftp user to ssh into his web directory in case he want to checkout from his git repo. 

### Steps to Reproduce:

- click on web
- click on web domain
- add sftp user
- login to ssh via root , 
- `nano /etc/passwd`
- find our sftp user we added above
- change its shell from `/usr/sbin/nologin`  to `/bin/rbash`
- now login to sftp user via ssh , it will login and will auto exit.

so how to allow sftp users to ssh

### Debian version:

Debian  10 

### VestaCP Version:

latest version

### Installed Software (what you got with the installer):

`
WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'
`

**Comment by myvesta** [comment]
just to check - you want to allow SFTP to user but user should not have SSH access?

**Comment by darkworks** [comment]
> just to check - you want to allow SFTP to user but user should not have SSH access?

no i want them to have ssh access to their directory under rbash shell . currently they can only browser files using ftp clients like file zilla / winscp  . but when they try to login to ssh , the putty window auto close upon login.

**Comment by darkworks** [comment]
found solution here : https://github.com/Skamasle/vestacp-jailkit-chroot
wondering it will work with myvesta or not ,  i guess will need testing , i think it will be good if its added to myvesta , will be good feature , by presenting checkbox an Additional FTP accounts area that check : to Allow user to ssh to its home directory , if user check checkbox then this code execute so that user can ssh to its home directory .

**Comment by myvesta** [comment]
Can't promise anything.
There are a lot of stuff that should be implemented.
Since I'm the only developer of myVesta fork, I just can be honest to you and say that some stuff will be implented in next 1-2-3 years, and some stuff maybe never :)

**Comment by darkworks** [comment]
no problem  i can understand :) 
however if ipv6 Belgium IT pull request is somehow mad working on this vesta fork , then it will be game changer all people will be using it so as new people will dive in development as official vesta seems dead
