### ISSUE TITLE
GSuite Gmail DKIM dns Record not validating

### ISSUE THREAD

**Issue by KashifHK123** [myvesta/vesta#84]
### Describe the problem:
Gsuite Gmail DKIM record not publish or validate from myVestacp DNS Setting

### Steps to Reproduce:

Here is details what i follow

Step 1: Create DKIM Record in Gsuite Gmail DKIM Setting
            DNS host name (TXT record name): google._domainkey
            TXT record value: v=DKIM1; k=rsa; p=******************

Step 2: Login myVestaCP  > DNS and go to desired domain and click on edit and replaced "Template: BIND9" from Default to Gmail.

Step 3:  myVestaCP  > DNS  > add record in desired domain
             Record: google._domainkey
             Type: TXT
             IP or Value: v=DKIM1; k=rsa; p=******************
             Click on Add

Step 4: Test DKIM record from mxtoolbox and from mail-tester
             Domain name: desired domain
             DKIM Selector: google._domainkey
             Query Answer: DNS Record not found or not publish 

### Debian version:

Debian 10

### VestaCP Version:

 0.9.8-26-33

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='proftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='mysql'
UPDATE_HOSTNAME_SSL='yes'

**Comment by KashifHK123** [comment]
@dpeca please review it.

**Comment by KashifHK123** [comment]
Problem Fixed by following these steps, just change key bit length from 2048 to 1024

Gsuite > App > Gmail > Authenticate Email  > Select DKIM key bit length:  2048 to 1024

**Comment by myvesta** [comment]
Yes, but that's just avoiding of bug.
Bug is old, inherited from offical Vesta.
Must see if Hestia eventually solved it.
Fix should be easy, just long TXT values should be splitted to:
`("firstPart" "seecondPart")`

**Comment by myvesta** [comment]
https://github.com/hestiacp/hestiacp/issues/678
will be fixed soon

**Comment by dpeca** [comment]
Here is the correct fix - https://github.com/serghey-rodin/vesta/commit/f74301b19f3f06edb80553574fbb29df489c2ee3
