### ISSUE TITLE
Login screen Disappear  

### ISSUE THREAD

**Issue by apurbajnu** [myvesta/vesta#85]
Login from disappeared. When I try to login I can see a white screen only. 
Besides this everything is working fine. Just I haven't access of my admin panel. I am new to Vesta. I have tried to restart vesta, apache and Nginx.  My password is working via ssh. 

### Debian version:
Debian 10

### VestaCP Version:
 0.9.8.26-33

 first 22 lines of file /usr/local/vesta/conf/vesta.conf

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='vsftpd'
DNS_SYSTEM='bind9'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
DISK_QUOTA='yes'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'

**Comment by myvesta** [comment]
You just need to access panel with your secret URL :)
You can find it in your emails.
