### ISSUE TITLE
multi-php-install.sh "Syntax error: "}" unexpected"

### ISSUE THREAD

**Issue by kbalicki** [myvesta/vesta#90]
### Describe the problem:
After running the script:

multi-php-install.sh: 62: multi-php-install.sh: Syntax error: "}" unexpected

### Steps to Reproduce:

copy/paste script and run

### Debian version:

Debian 10

### VestaCP Version:

MyVesta latest version

**Comment by myvesta** [comment]
Did you followed https://forum.myvestacp.com/viewtopic.php?f=18&t=52 ?

**Comment by kbalicki** [comment]
> Did you follow https://forum.myvestacp.com/viewtopic.php?f=18&t=52 ?

NO, I did not find this link, thank you!

**Comment by myvesta** [comment]
Try.
Re-open ticket if you still have problem.
