### ISSUE TITLE
домени Українською

### ISSUE THREAD

**Issue by serjiomati** [myvesta/vesta#91]
### Describe the problem:

Доброго дня, якщо писати домен Українською мовою то получаються ошибки
 apachectl[17902]: AH00526: Syntax error on line 3 of /home/admin/conf/web/s.\xd0\xba\xd1\x80\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x82247.\xd1\x83\xd0\xba\xd1\x80
s.кредит247
### Steps to Reproduce:

Type here what we should do in order to see the bug on our test server

### Debian version:

Type here, example: Debian 10

### VestaCP Version:

Type here, example: 0.9.8.26-29

### Installed Software (what you got with the installer):

MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM='local'
LANGUAGE='en'
VERSION='0.9.8'
DB_SYSTEM='pgsql,mysql'
UPDATE_HOSTNAME_SSL='yes'

**Comment by myvesta** [comment]
Write here domain address, and paste here content of `/home/admin/conf/web/s.\xd0\xba\xd1\x80\xd0\xb5\xd0\xb4\xd0\xb8\xd1\x82247.\xd1\x83\xd0\xba\xd1\x80` file

**Comment by serjiomati** [comment]
hello, i need disable open_basedir

**Comment by myvesta** [comment]
https://forum.myvestacp.com/viewtopic.php?f=18&t=54
second part of the post.
you can just comment `open_basedir` in pool.d conf file.
