### ISSUE TITLE
Problem with letsencrypt

### ISSUE THREAD

**Issue by sennevb** [myvesta/vesta#98]
### Describe the problem:

I added an extra subdomain on the panel, and got a Error: Let's Encrypt validation status
Without any info

I have been looking and  writing info to console by editing the v-add-letsencrypt-domain scrypt

All my aliases are working fine except for the www.domain.com the validation check is returning nothing

### Steps to Reproduce:
v-add-letsencrypt-domain2 'sennevb' zelfbouw-domotica.be 'www.zelfbouw-domotica.be'
nonce
0004wO4kEGsMraYPwUMBxLfVq2OG9_hmIU4JKCWc9m23x2A  status:   200
step 3 - auth token
url:  https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996737/eDHI1g 3gZI3b6xTuIurlDCje6eydNm2gkJ5LCU0PaafU0-ciI - token : 3gZI3b6xTuIurlDCje6eydNm2gkJ5LCU0PaafU0-ciI  - nonce : 00046RRhLin4fJFz45puBrqFyilfv38B3vtFtXG1Db0P9qw  - status :  200
default nginx method used
conf =  /home/sennevb/conf/web/nginx.zelfbouw-domotica.be.conf_letsencrypt
validation_check :
answer:
Error: Let's Encrypt validation status

All the extra data you see is data i added to debug the problem

v-add-letsencrypt-domain2 'sennevb' zelfbouw-domotica.be 'media1.zelfbouw-domotica.be'
nonce
0103boZajTjt_b58u7CqnqYZTVaBxETR2rverrO1-W-EJuY  status:   200
step 3 - auth token
url:  https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996735/RmFqlQ - token : 4a8J_V3iqY2z2jdzPiQC4HmLzr4ijTUnnXeqgVyvQrU  - nonce : 0003_q3wO_J6u7z6y9QP4mbcKz2HodOQGEe0IlHsY4dlCzw  - status :  200
default nginx method used
conf =  /home/sennevb/conf/web/nginx.zelfbouw-domotica.be.conf_letsencrypt
validation_check :  "status": "valid", "status": "valid",
step 3 - auth token
url:  https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996739/MWuSVg - token : 9mQoERAJz197S7pRSLFrs3s8xe5pkCZI8PJ1sOIjeNQ  - nonce : 0003CkzvHzDQ7v7Ux6IFL6xWd7r6EiPF1scOm3EWN8w-ZQM  - status :  200
default nginx method used
conf =  /home/sennevb/conf/web/nginx.zelfbouw-domotica.be.conf_letsencrypt
validation_check :  "status": "valid", "status": "valid",

### Debian version:

Debian 9

### VestaCP Version:

myVesta 0.9.8-26-37

### Installed Software (what you got with the installer):

WEB_SYSTEM='apache2'
WEB_RGROUPS='www-data'
WEB_PORT='8080'
WEB_SSL_PORT='8443'
WEB_SSL='mod_ssl'
PROXY_SYSTEM='nginx'
PROXY_PORT='80'
PROXY_SSL_PORT='443'
STATS_SYSTEM='webalizer,awstats'
FTP_SYSTEM='vsftpd'
MAIL_SYSTEM='exim4'
ANTIVIRUS_SYSTEM='clamav-daemon'
ANTISPAM_SYSTEM='spamassassin'
IMAP_SYSTEM='dovecot'
CRON_SYSTEM='cron'
FIREWALL_SYSTEM='iptables'
FIREWALL_EXTENSION='fail2ban'
BACKUP_SYSTEM=''
LANGUAGE='nl'
VERSION='0.9.8'
DB_SYSTEM='mysql'
DISK_QUOTA='no'

**Comment by sennevb** [comment]
I outputted more to console and it seems that this domain keeps the pending status:

 { "identifier": { "type": "dns", "value": "www.zelfbouw-domotica.be" }, "status": "pending", "expires": "2020-11-28T06:36:04Z", "challenges": [ { "type": "http-01", "status": "pending", "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996737/eDHI1g", "token": "3gZI3b6xTuIurlDCje6eydNm2gkJ5LCU0PaafU0-ciI" }, { "type": "dns-01", "status": "pending", "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996737/xPdajg", "token": "3gZI3b6xTuIurlDCje6eydNm2gkJ5LCU0PaafU0-ciI" }, { "type": "tls-alpn-01", "status": "pending", "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/8755996737/WVfosQ", "token": "3gZI3b6xTuIurlDCje6eydNm2gkJ5LCU0PaafU0-ciI" } ] }

Is there any way to fix this or do i have to wait till the expiry date? (hope not)

**Comment by myvesta** [comment]
always check on https://mxtoolbox.com/DNSLookup.aspx
both www.domain.com and domain.com
to be sure if it's pointing to your IP

**Comment by sennevb** [comment]
> always check on https://mxtoolbox.com/DNSLookup.aspx
> both [www.domain.com](http://www.domain.com) and domain.com
> to be sure if it's pointing to your IP

they do... i just checked, i didnt change dns so..
