### ISSUE TITLE
DNS error after run install script 

### ISSUE THREAD

**Issue by akunich** [myvesta/vesta#99]
I am Sorry for bad english.
I run  the installation on a clean debian 10.
During the installation, script noticed the "Temporary failure resolving 'ftp.debian.org'" error.
http://joxi.ru/4AkZ9JEFoO3nk2?d=1

The reason for this is because the INPUT DROP firewall policies have been added.

This is old problem original vesta. 

To fix the situation, you need to add to the firewall the one rule.

iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT

**Comment by myvesta** [comment]
But I never seen such issue.
Obviously it's related to Debian image that your hosting provider is providing to you.

Can you bring fresh installed Debian and then to run `iptables -L` and paste here.

**Comment by akunich** [comment]
I work as a Linux admin. And I faced this problem regularly in the original vesta. There, the installation working without errors, and after that I immediately add this rule.
I used to install the fresh LXC template Debian 10 from the Proxmox VE 6.3 repository
Now I've deployed a new container from the same template. Iptables rules are empty there http://joxi.ru/xAe8OkXfRQQJ12?d=1

I guess the reason is similar to the one described here
https://serverfault.com/questions/208942/iptables-blocking-dns/209019

When I first encountered this problem in vesta, I figured out this request in more detail. It became clear that dnslookup needed to allow incoming udp connections to source port 53 for it to work.
The state module is just more versatile.

By the way, iptables after the VPS reboot (forgot to make my rule permanent). Dnslookup doesn't work.
http://joxi.ru/8An39MNUzLLz0r?d=1

**Comment by myvesta** [comment]
It's really strange.
I installed Debian on many platforms... many different datacenters... never seen such issue.

So, if I understand, after reboot, if you additionally execute `iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT` your server start to resolve dnslookup ?

I just saw that it already exists: https://github.com/myvesta/vesta/blob/master/bin/v-update-firewall#L63-L67

So, obviously answer is here: https://github.com/myvesta/vesta/blob/master/bin/v-update-firewall#L42

I guess, when you run:
```
/sbin/sysctl net.netfilter.nf_conntrack_max
echo $?
```
you will get some error and positive result in echo?

for example, this is what I got:
```
root@test:~# /sbin/sysctl net.netfilter.nf_conntrack_max
net.netfilter.nf_conntrack_max = 65536
root@test:~# echo $?
0
```

**Comment by akunich** [comment]
Exactly. 
The reason is somewhere here. Lately I have been working with Proxmox VE a lot. I setup vesta in non-privileged LXC containers. There simply are not enough rights on container to read this variable.
http://joxi.ru/KAxg7KMsZ7ydJ2?d=1
On the host node this module is loaded
http://joxi.ru/52aJZOefEKMLpA?d=1

**Comment by akunich** [comment]
Recently delivered to another VestaCP client. There was no such problem. It looks like they are already Provide this option (lxc container).
https://github.com/hestiacp/hestiacp/blob/main/bin/v-update-firewall#L77

**Comment by myvesta** [comment]
Yup, looks like that's all we need to implement - https://github.com/hestiacp/hestiacp/commit/ad75b429d8274f064e0b4f2263598453be0b36e9#diff-f2f5fd20342d18f8a89fbbb8b295d48ab15b271fb0824fd6f910844973bb1b4e

Thanks to @ScIT-Raphael again :D <3

Can you add that line and reboot VM and see if it solved problem?

**Comment by akunich** [comment]
I apologize. Do you happen to speak Russian? It would be much faster to discuss this in telegrams or watsapp)). Here I think it is not entirely appropriate to write in Russian. It takes a lot of time to format thoughts in English (

**Comment by myvesta** [comment]
Unfortunately, not :)
I'm from Serbia and I never learned Russian in school :)

**Comment by akunich** [comment]
Ok )). Today, closer to midnight, I will restart the VPS and write about the result.

**Comment by myvesta** [comment]
just first implement line https://github.com/hestiacp/hestiacp/blob/main/bin/v-update-firewall#L77

**Comment by akunich** [comment]
Added a line, rebooted. The rule has not appeared. Manually launched v-update-firewall
The rule has appeared.
Probably v-update-firewall not runing on system boot.
But I think this can be considered a solution to the problem, because when new installing the vesta, the rule will be added and saved by a script in /etc/iptables.rules

**Comment by ScIT-Raphael** [comment]
> Thanks to @ScIT-Raphael again :D <3

@myvesta you're welcome ;)

**Comment by myvesta** [comment]
then what is running on system boot if not `v-update-firewall`  😐
i will check tomorrow...

**Comment by myvesta** [comment]
https://github.com/myvesta/vesta/blob/master/bin/v-update-firewall#L166

looks like it's fixed at the moment you manually run `v-update-firewall`
or, in other words, on next reboot "fresh version" will be executed

ok, i'll apply fix in official code

**Comment by myvesta** [comment]
Fixed - https://github.com/myvesta/vesta/commit/5be1e2d56d5942634e6477d0f4f81715ff208a2e
